gravitee-io/gravitee-docs

- src/main/asciidoc/docinfo.html
- src/main/asciidoc/index-docinfo.html
> fix: move links to https instead of http

- pages/apim/installation-guide/installation-guide-management-webui.adoc
This was already mentioned in the preview version of the document. However I still missed that point. I hope that this slight modification will make it even more obvious that baseURL has to point to Management API instamce. Plus there is no "angular.module(" in actual file.
> Minor modification to UI installation guide to reiterate that baseURL has to be properly configured

- pages/apim/installation-guide/installation-guide-portal-configuration.adoc
I've done a copy of the default json to make the upgrade.
Even if you highlighted that base_url is mandatory, it's easier to have it in the json sample...
> Add base_url in json sample

- pages/apim/user-guide/publisher/expression-language.adoc
In the expression language properties, path was missing (give a string with the full path).
> docs: add path property

- pages/ae/installation-guide/installation-guide-configuration.adoc
This closes https://github.com/gravitee-io/gravitee-alert-engine/issues/18
> fix: Hazelcast config is not correct in gravitee.yml

- pages/ae/installation-guide/installation-guide-configuration.adoc
This closes gravitee-io/gravitee-alert-engine#22
> fix: Unable to connect cluster remotely

- pages/apim/installation-guide/installation-guide-management-api-configuration.adoc
The subject template value is missing from the documentation about smtp configuration.
> add subject template value to smtp configuration

- pages/apim/installation-guide/partial/how-to-configure.adoc
add syntax for handling arrays in environment variables.
refers to issue #2490
> doc() : environment variables as array

- pages/am/2.x/quickstart/profile-information.adoc
If you need to specify the scope, it's not optional.
> scope is required

- pages/apim/installation-guide/installation-guide-repositories-elasticsearch.adoc
Closes gravitee-io/issues#2513
> feat(reporter): remove Elasticsearch 2.x support from documentation

- pages/apim/installation-guide/installation-guide-repositories-mongodb.adoc
Gateway can't start without readWrite (createIndex) on 'commands' collection.
I don't know if there is other collections right missing.
> apim: Updated MongoDB Client security gw missing RW on  'commands' collection.

- pages/am/3.x/installation-guide/installation-guide-gateway-install-zip.adoc
When you test if AM gateway is running the response is:
```
curl -X GET http://localhost:8092
No security domain matches the request
```
> Wrong response in AM Gateway test

- pages/apim/3.x/installation-guide/docker/installation-guide-docker_compose.adoc
ES requires special folder permissions when bind-mounting a local directory as explained [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_configuration_files_must_be_readable_by_the_elasticsearch_user)
> Update docs with ES folder permissions

- _data/sidebars/apim_3_x_sidebar.yml
- pages/apim/3.x/dev-guide/dev-guide-policies.adoc
- pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-stack.adoc
- pages/apim/3.x/installation-guide/docker/installation-guide-docker_compose.adoc
- pages/apim/3.x/installation-guide/docker/installation-guide-docker_customize.adoc
- pages/apim/3.x/installation-guide/docker/installation-guide-docker_images.adoc
- pages/apim/3.x/installation-guide/gateway/installation-guide-gateway-configuration.adoc
- pages/apim/3.x/installation-guide/red-hat/installation-guide-redhat-stack.adoc
- pages/apim/3.x/installation-guide/repositories/installation-guide-repositories-elasticsearch.adoc
- pages/apim/3.x/installation-guide/repositories/installation-guide-repositories-mongodb.adoc
- pages/apim/3.x/installation-guide/repositories/installation-guide-repositories.adoc
- pages/apim/3.x/installation-guide/with-zip/installation-guide-gateway-install-zip.adoc
- pages/apim/3.x/installation-guide/with-zip/installation-guide-management-ui-install-zip.adoc
- pages/apim/3.x/quickstart/api-consumer/api-consumer-api.adoc
- pages/apim/3.x/quickstart/api-consumer/api-consumer-test.adoc
- pages/apim/3.x/quickstart/api-consumer/api-consumer-ui.adoc
- pages/apim/3.x/quickstart/api-publisher/api-publisher-api.adoc
- pages/apim/3.x/quickstart/api-publisher/api-publisher-ui.adoc
- pages/apim/3.x/quickstart/quickstart-overview.adoc
- pages/apim/3.x/user-guide/publisher/documentation/publish-documentation.adoc
Fix https://github.com/gravitee-io/issues/issues/4380
> docs: improve documentation for quickstart

- pages/apim/3.x/dev-guide/dev-guide-policies.adoc
Example uses 1.2.0 - there's a much newer 1.8.0 available
> Use newer policy archetype in example

- pages/am/3.x/user-guide/identity-provider/database/userguide-database-identity-provider-inline.adoc
closes gravitee-io/issues#4695
> am: add password encoder for Inline identity provider

- pages/apim/3.x/installation-guide/configuration/gateway/installation-guide-gateway-configuration.adoc
Fixes https://github.com/gravitee-io/issues/issues/4744
⚠️ the reference to gravitee.yml does not exist for the moment (3.6.x)
> feat: auto-enable geoip and user_agent when elasticsearch > 7.x

- pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-mongodb.adoc
In relation to https://github.com/gravitee-io/issues/issues/5019.
This PR just adds the `authSource` option to the MongoDB configuration example.
> [#5019] Add authSource option to MongoDB configuration example

- .circleci/config.yml
**Issue**
NA
Setup CI to build the documentation on each PR to avoid any formatting error to be merged to `develop` and then `master`.
Example of failing build: 
https://app.circleci.com/pipelines/github/gravitee-io/gravitee-docs/4/workflows/fe6679d6-4696-4811-b804-eb16a0a43e7e/jobs/4
> ci: build documentation for each PR

- _config.yml
As APIM and AM new version are released, we need to update the documentation to display the current version.
> Prepare 3.11.0 release

- index.adoc
**Issue**
N.A.
Fix wrong link on home page
> fix(cockpit): wrong link on home page

- pages/ae/am/am-installation.adoc
- pages/ae/apim/apim-installation.adoc
**Issue**
gravitee-io/gravitee-alert-engine/issues/232
Documentation on how to configure the AE connector on APIM and AM to enable sending events to AE using http instead of websocket.
> docs(ae): add doc on how to send events over http

- pages/ae/am/am-installation.adoc
- pages/ae/apim/apim-installation.adoc
Version of AE needed to send event over http is 1.5.0 not 1.5.1
> docs(ae): fix ae minimum version for http events to 1.5.0

- Dockerfile
- Dockerfile-build
**Issue**
Ruby Gem build is failing due to the image change which doesn't include the `build-essential` utilities.
I have added the required package in part of the Dockerfiles which should now allow for the Dockerfiles to be build.
> fix: ruby gem build

- pages/am/3.x/user-guide/user-management/password/user-guide-password-policy.adoc
**Issue**
Password policies: 
https://github.com/gravitee-io/issues/issues/6520
https://github.com/gravitee-io/issues/issues/6521
Added documentation to Password policy dictionary and user profile 
https://github.com/gravitee-io/gravitee-access-management/pull/1456
https://github.com/gravitee-io/gravitee-access-management/pull/1459
> docs: password policy dictionary and user profile

- _data/sidebars/apim_3_x_sidebar.yml
- _data/sidebars/cockpit_sidebar.yml
- pages/am/3.x/user-guide/mfa/user-guide-mfa-step_up.adoc
- pages/apim/3.x/installation-guide/configuration/gateway/installation-guide-gateway-configuration.adoc
**Issue**
gravitee-io/issues#5888
Document the ability to configure gateway keystore (to enable SSL) using either file or kubernetes (secret or configmap)
> docs(cert): support for auto reload certificate when updated

- pages/am/3.x/user-guide/identity-provider/user-guide-mapping-identity-provider.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/6515
The issue aims to separate roles given from Identity Provider role mappers to the assigned roles.
https://github.com/gravitee-io/gravitee-access-management/pull/1469
> docs: SCIM role mapper warning

- _data/sidebars/am_3_x_sidebar.yml
- pages/am/3.x/breaking-changes/breaking-changes-3.15.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/6516
`openid` does not imply `full_profile` anymore
https://github.com/gravitee-io/gravitee-access-management/pull/1480
> feat: exclude full_profile with openid only

- pages/node/partial/metrics.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/6924
Add documentation about prometheus configuration and the possibility to choose old label names.
Not sure about the text or the place in the page. Please comment !!
> doc(metrics): add configuration to use old labels

- _data/sidebars/cockpit_sidebar.yml
**Issue**
N.A.
I've noticed that the develop branch have been [merged to master](https://github.com/gravitee-io/gravitee-docs/commit/b563b7e523bd0440e81016225268af4ab2cceb5a). This caused the Cockpit documentation for API Designer to be published on the [docs website](https://docs.gravitee.io/cockpit/3.x/cockpit_userguide_api_designer.html).
But Cockpit API Designer is not available in 3.15 so we need to remove this part of documentation from the website.
I just removed the entry from the menu but kept the pages for the next version.
> fix: remove Cockpit API Designer doc (not included in 3.15)

- pages/apim/3.x/user-guide/publisher/import-apis.adoc
https://github.com/gravitee-io/issues/issues/7003
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-import-api-documentation/index.html)
> docs: add placeholders in import API documentation curls URLs

- .circleci/config.yml
bash syntax typo when assigning a variable 🤦🏻‍♂️
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-purge-container-workflow/index.html)
> fix containers purge workflow

- .circleci/config.yml
The storage command of azure cli needs an overwrite flag set to true
since v2.34.0
see https://github.com/Azure/azure-cli/issues/21477
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-deployment-on-azure-storage/index.html)
> ci: add overwrite flag to az storage upload

- _data/sidebars/apim_3_x_sidebar.yml
**Issue**
No issue linked
Adding a missing link to import API documentation page in sidebar
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/add-link-to-import-doc/index.html)
> add missing link in sidebar

- _config.yml
Update doc for the 3.16.1 release
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-3-16-1/index.html)
> docs: release of 3.16.1

- pages/apim/3.x/user-guide/publisher/design-studio/design-studio-create.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/6654
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/6654-best-match-improvment/index.html)
> fix: best match flow mode should select only the best match

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.17.0/README.adoc
https://github.com/gravitee-io/issues/issues/7097
docs: add APM 3.17 upgrade guide
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-apim-317-upgrade-guide/index.html)
> docs: add APM 3.17 upgrade guide

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.15.6/README.adoc
- pages/apim/3.x/installation-guide/upgrades/3.16.2/README.adoc
- pages/apim/3.x/installation-guide/upgrades/3.17.0/README.adoc
Add missing breaking changes (after support release) and remove env-github[]
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/add-missing-bc/index.html)
> Add missing breaking change in APIM 3.17 documentation

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.10.13/README.adoc
docker breaking change for 3.10.13
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/apim-3-10-13-breaking/index.html)
> docs: add missing breaking changes

- pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-redis.adoc
**Issue**
Not an issue
Or related to the old https://github.com/gravitee-io/issues/issues/79
Adding redis sentinel config example.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/feature-rate-limit-repo-redis/index.html)
> ADD redis sentinel config example

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.18.0/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/6079
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-alertsscopetoenv-upgradenote/index.html)
> docs: 3.18 upgrade note about platform alerts scoped to environment

- pages/am/3.x/installation-guide/configuration/installation-guide-configuration.adoc
- pages/am/3.x/installation-guide/configuration/installation-guide-gateway-configuration.adoc
- pages/am/3.x/installation-guide/configuration/installation-guide-management-api-configuration.adoc
- pages/am/3.x/installation-guide/configuration/installation-guide-repositories-mongodb.adoc
- pages/apim/3.x/installation-guide/configuration/gateway/installation-guide-gateway-configuration.adoc
- pages/apim/3.x/installation-guide/configuration/rest-apis/installation-guide-rest-apis-configuration.adoc
- pages/cockpit/configuration-guide/installation-guide-configuration.adoc
The mongodb configuration is missing the keystore parameters in a lot of places, especially where the full documentation should be.
Documents the changes done in https://github.com/gravitee-io/gravitee-repository-mongodb/pull/83
> Update documentation for mongodb parameters, notable keystore related

- pages/apim/3.x/policy-reference/policy-javascript.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/7179
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/update-javascript-policy/index.html)
> docs(apim): add warning on return content instruction

- pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/6563
docs(apim): add note about JDBC rate limit limitations
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-jdbcratelimitlimit/index.html)
> docs(apim): add note about JDBC rate limit limitations

- pages/apim/3.x/installation-guide/upgrades/3.17.0/README.adoc
see https://github.com/gravitee-io/issues/issues/7610
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-add-upgrade-script-for-3-17/index.html)
> fix: add upgrade script link for 3.17.0

- _config.yml
- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.10.1/README.adoc
- pages/apim/3.x/installation-guide/upgrades/3.17.3/README.adoc
**Issue**
N/A
APIM 3.17.3 has been released
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/integrate-elasticsearch-repository-in-apim/index.html)
> APIM 3.17.3 has been released

- pages/apim/3.x/installation-guide/upgrades/3.18.0/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/7620
add a breaking change note for the renaming of `gravitee-repository-elasticsearch`
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/move-reporter-elasticsearch-in-apim-repo-master/index.html)
> upgrade note for the ES repository renaming - 3.18.0

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.15.9/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/7620
add a breaking change note for the renaming of `gravitee-repository-elasticsearch`
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/move-reporter-elasticsearch-in-apim-repo-3-15-x/index.html)
> upgrade note for the ES repository renaming - 3.15.9

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.10.15/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/7620
add a breaking change note for the renaming of `gravitee-repository-elasticsearch`
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/move-reporter-elasticsearch-in-apim-repo-3-10-x/index.html)
> upgrade note for the ES repository renaming - 3.10.15

- pages/apim/3.x/installation-guide/upgrades/3.19.0/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/7360
docs(apim): add note for cache managers in apim 3.19.0 upgrade
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-apikeysandsubsmanagers/index.html)
> docs(apim): add note for cache managers in apim 3.19.0 upgrade

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.10.19/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/7824
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-plansbreakingchange-3-10/index.html)
> docs: document security chain change in 3.10.19 upgrade note

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.18.5/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/7836
Adding a breaking change information in APIM upgrade guide regarding the portal API.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/7836-apim-3-18-x-bc-portal-api/index.html)
> doc: add a breaking change information for APIM 3.18.5 about portal API

- pages/apim/3.x/installation-guide/hybrid/installation_guide_hybrid_deployment.adoc
This fixes 2 broken links.
And rephrases the "remove useless plugin" part, which was really confusing : some users were removing the listed plugins but they have to be kept.
(And the APIM 1.18.0 example was outdated)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-improvebridgedoc/index.html)
> docs: APIM bridge gateway documentation improvement

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.15.14/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/8165
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-plansbreakingchange-3-15/index.html)
> docs: document security chain change in 3.15.14 upgrade note

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.18.7/README.adoc
:warning: Merge before releasing APIM 3.18.7 :warning: 
This add upgrade guide for APIM 3.18.7, with the same breaking change that is already in 3.15.14 upgrade guide.
**Issue**
https://github.com/gravitee-io/issues/issues/8167
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-3-18-7-upgradenote/index.html)
> docs: add APIM 3.18.7 upgrade note

- pages/apim/3.x/installation-guide/upgrades/3.10.19/README.adoc
- pages/apim/3.x/installation-guide/upgrades/3.15.14/README.adoc
- pages/apim/3.x/installation-guide/upgrades/3.18.7/README.adoc
DOC-225 Replaced warning note in upgrade notes for APIM 3.10.19 / 3.15.14 / 3.18.7
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-225
DOC-225 Replaced warning note in upgrade notes for APIM 3.10.19 / 3.15.14 / 3.18.7
> DOC-225 Replaced warning note in upgrade notes for APIM 3.10.19 / 3.15.14 / 3.18.7

- _config.yml
- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.18.9/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/8421
add breaking change information about the return of `/apis/{apiId}/subscribers`
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/8421-improve-api-subscriptions-page-loading/index.html)
> add breaking change information about the return of a resource

- pages/apim/1.x/changelog.adoc
- pages/apim/3.x/changelog.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/8186
Following the changes on the changelog generation in the APIM project, here we change the APIM changelogs locations
No real visual impact here
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-change-apim-changelog-location/index.html)
> docs(apim): change changelogs location

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
**Issue**
N/A
Just add the 3.18.10 inclusion in the migration guide. Otherwise, it won't be published.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-apim-3-18-10-upgrade-guide/index.html)
> fix: expose APIM 3.18.10 part in the migration guide

- pages/apim/3.x/installation-guide/hybrid/installation_guide_hybrid_deployment.adoc
Fix HTTP bridge server port
**Issue**
None
Update (fix) hybrid install doc, wrong port
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-hybrid-install-doc/index.html)
> FIX hybrid install doc

- pages/apim/3.x/installation-guide/upgrades/3.19.0/README.adoc
**Issue**
NA
Add breaking change info about the Console with a custom base URL
For extra details see https://github.com/gravitee-io/issues/issues/8518
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/add-missing-bc-in-3-19/index.html)
> Add breaking change info about Console with a custom base url

- pages/ae/apim/apim-installation.adoc
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-168
Add information block on the fact that since 3.18.0, a user does not have to download AlertEngine connector any more. It's embedded.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/add-information-about-alert-engine-connector/index.html)
> docs: add basic information on new AE connector in 3.18.0

- _config.yml
**Issue**
N/A
Add new Alert-Engine release 1.6.6
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-release-ae-1-6-6/index.html)
> docs: include new AE release 1.6.6

- _config.yml
Bump latest version of AE to 1.6.7
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/ae-1-6-7/index.html)
> docs: bump AE latest version to 1.6.7

- pages/apim/3.x/installation-guide/configuration/installation-guide-cache.adoc
- pages/apim/3.x/user-guide/publisher/resources/resource-cache-redis.adoc
DOC-287 Fixed some bad links and updated Redis Cache Resource page in the publisher guide with more relevant links
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-287
DOC-287 Fixed some bad links and updated Redis Cache Resource page in the publisher guide with more relevant links
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-287/index.html)
> DOC-287 Fixed some bad links and updated Redis Cache Resource page

- pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-management-context.adoc
The current Gravitee Kubernetes Operator management context example is wrong. The auth object contains a `credentials` attribute and not another `auth`
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/apim-gko-auth/index.html)
> docs(apim): correct gko management context example

- pages/apim/3.x/changelog/changelog-3.15.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.15.19/pages/apim/3.x/changelog/changelog-3.15.adoc)
Here is some information to help with the writing: 
<details>
- feat: handle alert email-notifier and default-email authMethods
- fix(apim): remove metadata name placeholder
- fix: escape all special characters when looking for a user
</details>
[See all Jira issues for 3.15.x version](https://gravitee.atlassian.net/jira/software/c/projects/APIM/issues/?jql=project%20%3D%20%22APIM%22%20and%20fixVersion%20%3D%203.15.x%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
🚀 CI was able to deploy the build of this PR, so you can now try it directly …
> [APIM] Add changelog for new 3.15.19 release

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.14/pages/apim/3.x/changelog/changelog-3.18.adoc)
<details>
- perf(mongodb): optimize database access when searching APIs
- fix: pagination class was not well created
- fix: manage multiple accept headers with quality factor https://gravitee.atlassian.net/browse/APIM-143
- fix: handle dynamic property changes on deploy
- fix: handle schedule in dynamic property ui
- fix: trigger search on api subscriptions component init
- fix: restore archived applications in log filters
- fix(gateway): map ssl configuration to debug http server
- fix: catch plan not found exception when …
> [APIM] Add changelog for new 3.18.14 release

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.20.0/README.adoc
**Issue**
N/A
Add breaking change note in APIM upgrade guide about AE new default behaviour
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/add-note-in-apim-upgrade-guide/index.html)
> add breaking change note in APIM upgrade guide about AE new default behaviour

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.15.20/README.adoc
**Issue**
N/A
Since APIM 3.15.20, we use the version 2.0.0 of the XSLT policy that comes with a breaking change in the configuration.
This PR warns users about this change
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/breaking-change-in-policy-xslt/index.html)
> docs: add upgrade guide for 3.15.20

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.18.15/README.adoc
**Issue**
N/A
Since APIM 3.18.15, we use the version 2.0.0 of the XSLT policy that comes with a breaking change in the configuration.
This PR warns users about this change
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/apim-3-18-15/index.html)
> Update upgrade guide for APIM 3.18.15

- pages/apim/3.x/changelog/changelog-3.15.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.15.21/pages/apim/3.x/changelog/changelog-3.15.adoc)
<details>
- fix: handle flow step order in database
</details>
[See all Jira issues for 3.15.x version](https://gravitee.atlassian.net/jira/software/c/projects/APIM/issues/?jql=project%20%3D%20%22APIM%22%20and%20fixVersion%20%3D%203.15.21%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-15-21/index.html)
> [APIM] Add changelog for new 3.15.21 release

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.15/pages/apim/3.x/changelog/changelog-3.18.adoc)
<details>
- fix(postgreSQL): 3.18.0 migration script handle existing commands
- fix: recalculate plan general conditions page id during API import
- fix: check application apiKey mode according to environment in request
- fix: API deserialization set plan.api from api.id if not in definition
- fix: if dictionary provider method isn't defined then set it to GET
- fix(api): scope group associate by environment
- fix: add primary keys on all tables as MySQL cluster requires it
- fix: use correct permission to display Gateway menu …
> [APIM] Add changelog for new 3.18.15 release

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.16/pages/apim/3.x/changelog/changelog-3.18.adoc)
<details>
- fix(jdbc): handle query with page number higher than max page with data
- fix: handle flow step order in database
</details>
[See all Jira issues for 3.18.x version](https://gravitee.atlassian.net/jira/software/c/projects/APIM/issues/?jql=project%20%3D%20%22APIM%22%20and%20fixVersion%20%3D%203.18.16%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-18-16/index.html)
> [APIM] Add changelog for new 3.18.16 release

- pages/apim/3.x/installation-guide/upgrades/3.20.0/README.adoc
**Issue**
N/A
Since APIM 3.20.0, we use the version 2.0.0 of the XSLT policy that comes with a breaking change in the configuration.
This PR warns users about this change
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/add-xslt-policy-bc-in-upgrade-note/index.html)
> Add upgrade note about xslt policy breaking change

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.19.5/README.adoc
**Issue**
N/A
Since APIM 3.19.5, we use the version 2.0.0 of the XSLT policy that comes with a breaking change in the configuration.
This PR warns users about this change
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/upgrade-guide-3-19-5/index.html)
> Update upgrade guide for APIM 3.19.5

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.17/pages/apim/3.x/changelog/changelog-3.18.adoc)
<details>
- fix: disable checksum validation on liquibase 3.18.0 changeset
</details>
[See all Jira issues for 3.18.x version](https://gravitee.atlassian.net/jira/software/c/projects/APIM/issues/?jql=project%20%3D%20%22APIM%22%20and%20fixVersion%20%3D%203.18.17%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-18-17/index.html)
> [APIM] Add changelog for new 3.18.17 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.5/pages/apim/3.x/changelog/changelog-3.19.adoc)
<details>
- fix(jdbc): handle query with page number higher than max page with data
- fix: handle flow step order in database
- fix(postgreSQL): 3.18.0 migration script handle existing commands
- fix: API deserialization set plan.api from api.id if not in definition
- fix: handle wildcard in SimpleFailureProcessor
- fix: use key attribute instead id in the categories of an API
- fix: check subscriptions ids before evict
- fix: disable DOCTYPE usage for wsdl imports
- fix: handle huge payload from cockpit controller
- fix(search): …
> [APIM] Add changelog for new 3.19.5 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.6/pages/apim/3.x/changelog/changelog-3.19.adoc)
<details>
- fix: disable checksum validation on liquibase 3.18.0 changeset
</details>
[See all Jira issues for 3.19.x version](https://gravitee.atlassian.net/jira/software/c/projects/APIM/issues/?jql=project%20%3D%20%22APIM%22%20and%20fixVersion%20%3D%203.19.6%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-19-6/index.html)
> [APIM] Add changelog for new 3.19.6 release

- pages/apim/3.x/installation-guide/red-hat/installation-guide-redhat-stack.adoc
**Issue**
N/A
Fix a small issue in RedHat documentation
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/improvement-in-apim-rpm-installation/index.html)
> docs: the service name does not have "3x"

- pages/apim/3.x/changelog/changelog-3.19.adoc
**Issue**
NA
Use correct GitHub issue in `APIM - 3.19.5` changelog
Related to https://graviteeio.slack.com/archives/C02FBCEPQTT/p1674036414315009
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/gaetanmaisse-patch-1/index.html)
> fix: use correct GitHub issue in `APIM - 3.19.5` changelog

- pages/apim/3.x/changelog/changelog-3.15.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.15.22/pages/apim/3.x/changelog/changelog-3.15.adoc)
<details>
- fix(cockpit): make hello command reply update only organization
- fix(repository): change PK of flow_steps table to a new auto incremented column
</details>
[See all Jira issues for 3.15.x version](https://gravitee.atlassian.net/jira/software/c/projects/APIM/issues/?jql=project%20%3D%20%22APIM%22%20and%20fixVersion%20%3D%203.15.22%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
🚀 CI was able to deploy the build of this PR, so you can now try it directly …
> [APIM] Add changelog for new 3.15.22 release

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.18/pages/apim/3.x/changelog/changelog-3.18.adoc)
<details>
- fix: bump data-logging-masking policy for dev env to 2.0.3
- fix: fix error message displayed when trying to publish 2 keyless plan
- fix(jdbc): update flows condition max size to 512
- feat: websocket frame compression support
- fix(cockpit): make hello command reply update only organization
- fix(cockpit): make hello command reply update only organization
- fix: email notifier 1.5.0 with authMethods downgraded in 3.18.x
- fix: resolve deployment of an api with group as primary owner
- fix(repository): change PK of …
> [APIM] Add changelog for new 3.18.18 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.7/pages/apim/3.x/changelog/changelog-3.19.adoc)
<details>
- fix: validation messages are never displayed
- fix: bump swagger version
- fix: do not save clientId in APIKEY subscription
- fix: add search to log filters to improve performances
- fix: display icons of APIs in API list screen
- fix: API key synchronization gives precedence to active keys
- fix: bump data-logging-masking policy for dev env to 2.0.3
- fix: fix error message displayed when trying to publish 2 keyless plan
- fix(jdbc): update flows condition max size to 512
- feat: websocket frame compression support
- …
> [APIM] Add changelog for new 3.19.7 release

- pages/apim/3.x/installation-guide/installation-guide-migration.adoc
- pages/apim/3.x/installation-guide/upgrades/3.21.0/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/8862
https://gravitee.atlassian.net/browse/APIM-726
Add documentation for fix: when user sends POST request to /user/login without Auth --> return HTTP response 401
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/apim-726-fix-no-auth-return-200/index.html)
> fix(rest-api): return 401 when no Auth header at login

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.1/pages/apim/3.x/changelog/changelog-3.20.adoc)
<details>
- fix: sanitize name of new API
- fix: sanitize name and description of new Plan
- fix: sanitize name and description of new Application
- fix: sanitize firstname and lastname of NewExternalUserEntity
- fix: sanitize name of new API
- fix: sanitize name and description of new Plan
- fix: sanitize name and description of new Application
- fix: sanitize firstname and lastname of NewExternalUserEntity
- fix: update headers in API list screen
- fix(repository): change PK of flow_steps table to a new auto incremented column
- …
> [APIM] Add changelog for new 3.20.1 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.8/pages/apim/3.x/changelog/changelog-3.19.adoc)
<details>
- fix: display full query param values when they contain `=` in them
- fix: update user password policy regex
- fix: avoid adding Redoc script in dom dynamically
- fix: filter expired gateway started events
- fix: correctly handle IDP with name containing upper case character
- fix: evict properly subscriptions from cache
- fix: validation messages are never displayed
- fix: bump swagger version
- fix: set sync probe to true when caches are fully loaded
- fix: update validation spec in API proxy config schema form
- …
> [APIM] Add changelog for new 3.19.8 release

- pages/ae/overview/introduction.adoc
**Issue**
N/A
In AE introduction page, the link for asking a lincense is broken. This PR fix it.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-alert-engine-license-link/index.html)
> fix(AE): link to ee_license.adoc ee_licensing.html was broken

- pages/apim/3.x/user-guide/publisher/documentation/publish-documentation.adoc
**Issue**
https://gravitee.atlassian.net/browse/APIM-881
https://github.com/gravitee-io/issues/issues/7327
Improve documentation about the doc import using `.gravitee.json` by highlighting the rules the Gravitee descriptor must follow to be taken into account
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/update-fetcher-doc/index.html)
> Improve documentation about the doc import using `.gravitee.json`

- pages/apim/3.x/installation-guide/configuration/gateway/installation-guide-gateway-configuration.adoc
**Issue**
https://gravitee.atlassian.net/browse/APIM-75
gravitee-io/issues#7618
Add doc about the configuration of transaction and request id headers. 
Override mode will be available in 3.18.20+, 3.19.9+, 3.20.3+
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/apim-75-add-doc-about-backendoverridemode/index.html)
> Add doc about the configuration of transaction and request id headers

- pages/apim/3.x/changelog/changelog-3.18.adoc
- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.20/pages/apim/3.x/changelog/changelog-3.18.adoc)
<details>
- fix: skip page fetch on root pages
- fix: handle special characters in user/password of MongoDB uri
- fix: introduce a TransactionResponseProcessor
- fix: bump traffic shadowing version to 2.0.0
- fix: use JSON SCHEMA to convert YAML to JSON
- fix(gateway): configure stream before handling connection
- fix: bump `@gravitee/ui-components` to `3.38.8`
- fix: update status of original endpoint
- fix: filter by environment when searching APIs with SearchEngine
- fix: fix best match flow selector
- fix: optimize search …
> [APIM] Add changelog for new 3.18.20 release

- pages/apim/3.x/installation-guide/upgrades/3.21.0/README.adoc
Upgrade to 3.21 documentation
(https://www.tenable.com/audits/items/CIS_Docker_v1.3.1_L1_Docker_Linux.audit:bdcea17ac365110218526796ae3095b1)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docker-non-root/index.html)
> Docker non root

- pages/apim/3.x/kubernetes/apim-kubernetes-operator-definitions.adoc
Current GKO ManagementContext examples are wrong. Environment and organization ids are required when users try to push it on the cluster.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-mgmt-context/index.html)
> docs: add organization and environment ids in gko context definitions

- pages/apim/3.x/changelog/changelog-3.18.adoc
- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.9/pages/apim/3.x/changelog/changelog-3.19.adoc)
<details>
- fix: bump notifier-api & notifier email
- fix: bump elastic reporter to 3.12.5
- fix: allow underscore in hostname
- fix: display list of API members in the transfer ownership screen
- fix: log all timeouts when chaining calls
- fix: log all timeouts when chaining calls
- fix: escape uri components in log queries
- fix: escape uri components in log queries
- fix: bump gravitee-node to `1.25.3`
- fix: skip page fetch on root pages
- fix: skip page fetch on root pages
- fix: introduce a TransactionPostProcessor
- fix: …
> [APIM] Add changelog for new 3.19.9 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.3/pages/apim/3.x/changelog/changelog-3.20.adoc)
<details>
- fix: handle application with no group when sending notification
- fix: bump `policy-regex-threat-protection` to `1.3.3`
- fix: do not throw when sending notif to app owner with multiple subscription to the same API
- fix: bump `policy-regex-threat-protection` to `1.3.3`
- fix: do not throw when sending notif to app owner with multiple subscription to the same API
- fix: match documentation and implementation for attach media api
- fix: match documentation and implementation for attach media api
- fix: bump …
> [APIM] Add changelog for new 3.20.3 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.4/pages/apim/3.x/changelog/changelog-3.20.adoc)
<details>
- fix: delete definition context from api history
- fix: remove use of `ApiRepository.findAll`
- fix: allow use of personal token on the Portal API
- fix: add missing PK on `subscriptions_metadata` table
</details>
[See all Jira issues for 3.20.x version](https://gravitee.atlassian.net/jira/software/c/projects/APIM/issues/?jql=project%20%3D%20%22APIM%22%20and%20fixVersion%20%3D%203.20.4%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
🚀 CI was able to deploy the build of this PR, so you can now try it directly …
> [APIM] Add changelog for new 3.20.4 release

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.21/pages/apim/3.x/changelog/changelog-3.18.adoc)
<details>
- fix: make debug mode work with ssl or haproxy enabled
- fix: bump `@gravitee/ui-components` to `3.38.10`
- fix: delete definition context from api history
- fix: remove use of `ApiRepository.findAll`
- fix: allow use of personal token on the Portal API
- fix: handle application with no group when sending notification
- fix: bump `policy-regex-threat-protection` to `1.3.3`
- fix: do not throw when sending notif to app owner with multiple subscription to the same API
- fix: bump `gravitee-policy-ssl-enforcement` to …
> [APIM] Add changelog for new 3.18.21 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.10/pages/apim/3.x/changelog/changelog-3.19.adoc)
<details>
- fix: make debug mode work with ssl or haproxy enabled
- fix: bump `@gravitee/ui-components` to `3.38.10`
- fix: delete definition context from api history
- fix: remove use of `ApiRepository.findAll`
- fix: allow use of personal token on the Portal API
- fix: handle application with no group when sending notification
- fix: bump `policy-regex-threat-protection` to `1.3.3`
- fix: do not throw when sending notif to app owner with multiple subscription to the same API
- fix: match documentation and implementation for …
> [APIM] Add changelog for new 3.19.10 release

- apim/3.x/portal-api/3.20/index.html
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-openapi-link/index.html)
> fix: Typo in the OpenAPI spec extension for the 3.20 of the portal API

- _config.yml
- _data/sidebars/am_3_x_sidebar.yml
- pages/am/3.x/breaking-changes/breaking-changes-4.0.adoc
- pages/am/3.x/breaking-changes/breaking-changes.adoc
- pages/am/3.x/installation-guide/installation-guide-migration.adoc
related-to AM-63
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-63-add-migrationguide/index.html)
> fix(am): addition of migration note for 4.0 about MongoDB indexes

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.11/pages/apim/3.x/changelog/changelog-3.19.adoc)
<details>
- fix: use group default roles if exists when adding members
- feat: add option to use pkce authent in swagger doc page
- feat: add option to use pkce authent in swagger doc page
- fix: use group default roles if exists when adding members
- fix: set id_token_hint on logout request when user authenticated with OIDC provider
- fix: set id_token_hint on logout request when user authenticated with OIDC provider
- fix: use the right route to redirect to studio
- fix: use the right route to redirect to studio
- fix: apply …
> [APIM] Add changelog for new 3.19.11 release

- .circleci/config.yml
- Gemfile.lock
**Issue**
N/A
By updating the gemlock file, the cache key computed in circleci jobs will be reset and a new cache will be used.
> Improve cache in circleCI workflow

- pages/apim/3.x/installation-guide/configuration/gateway/installation-guide-gateway-configuration.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-default-conf-link/index.html)
> fix: Update default gravitee.yml conf link to use the Gravitee DNS

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.23/pages/apim/3.x/changelog/changelog-3.18.adoc)
<details>
- fix: compute application apis subscribers links
- fix: bump `gravitee-policy-request-validation` to `1.13.1`
- fix: bump `gravitee-policy-ssl-enforcement` to `1.2.3`
- fix: bump `gravitee-node` to `1.24.7`
- fix: ignore author picture for api promotions
- fix: search for subscribers in logs in an api context
- fix: markdown sanitization should be activated by default.
- fix: use conditional policies to convert a V1 API
- fix: security policy migration
- fix: escaped search query when searching for a context path
- fix: …
> [APIM] Add changelog for new 3.18.23 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.6/pages/apim/3.x/changelog/changelog-3.20.adoc)
<details>
- fix: compute application apis subscribers links
- fix: bump `gravitee-policy-request-validation` to `1.13.1`
- fix: bump `gravitee-policy-ssl-enforcement` to `1.2.3`
- fix: bump `gravitee-node` to `2.0.7`
- fix: ignore author picture for api promotions
- fix: search for subscribers in logs in an api context
- fix: markdown sanitization should be activated by default.
- fix: use conditional policies to convert a V1 API
- feat: add resource to set api definition context
- fix: escaped search query when searching for a …
> [APIM] Add changelog for new 3.20.6 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.12/pages/apim/3.x/changelog/changelog-3.19.adoc)
<details>
- fix: compute application apis subscribers links
- fix: bump `gravitee-policy-request-validation` to `1.13.1`
- fix: bump `gravitee-policy-ssl-enforcement` to `1.2.3`
- fix: bump `gravitee-node` to `1.25.6`
- fix: ignore author picture for api promotions
- fix: search for subscribers in logs in an api context
- fix: markdown sanitization should be activated by default.
- fix: use conditional policies to convert a V1 API
- fix: escaped search query when searching for a context path
- fix: apply default role if user is …
> [APIM] Add changelog for new 3.19.12 release

- pages/am/3.x/installation-guide/configuration/installation-guide-repositories-jdbc.adoc
AM embed the jdbc plugin so no need to ask users to add it 
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-jdbc-repo-plugin/index.html)
> No need to add the jdbc plugin anymore

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.24/pages/apim/3.x/changelog/changelog-3.18.adoc)
<details>
- fix(console): add hash to get api picture & background
- fix: bump gravitee-node to fix OS license check issue
- fix(portal): bump ui-component to keep name text aline left when is long string
- fix: handle null value in role mapping
- fix(console): keep existing api picture / background on rollback if exist
- fix: add config to set referral when using LDAP
- fix(console): fix a focus bug when editing properties
- feat(console): application search can be done by application id
- fix: check correct permission to get …
> [APIM] Add changelog for new 3.18.24 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.13/pages/apim/3.x/changelog/changelog-3.19.adoc)
<details>
- fix(console): add hash to get api picture & background
- fix(portal): bump ui-component to keep name text aline left when is long string
- fix: bump gravitee-node to fix OS license check issue
- fix: handle null value in role mapping
- fix(console): keep existing api picture / background on rollback if exist
- fix: add config to set referral when using LDAP
- fix(console): fix a focus bug when editing properties
- fix: check correct permission to get dictionary https://gravitee.atlassian.net/browse/APIM-1565 …
> [APIM] Add changelog for new 3.19.13 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.7/pages/apim/3.x/changelog/changelog-3.20.adoc)
<details>
- fix(console): add hash to get api picture & background
- fix: bump gravitee-node to fix OS license check issue
- fix(portal): bump ui-component to keep name text aline left when is long string
- fix: handle null value in role mapping
- fix(console): keep existing api picture / background on rollback if exist
- fix: add config to set referral when using LDAP
- fix(console): fix a focus bug when editing properties
- fix: check correct permission to get dictionary https://gravitee.atlassian.net/browse/APIM-1565 …
> [APIM] Add changelog for new 3.20.7 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.8/pages/apim/3.x/changelog/changelog-3.20.adoc)
<details>
- fix: bump `gravitee-policy-cache` to `1.16.0`
</details>
[See all Jira issues for 3.20.x version](https://gravitee.atlassian.net/jira/software/c/projects/APIM/issues/?jql=project%20%3D%20%22APIM%22%20and%20fixVersion%20%3D%203.20.8%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
> [APIM] Add changelog for new 3.20.8 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.9/pages/apim/3.x/changelog/changelog-3.20.adoc)
<details>
- fix: remove requirement on repository CACHE scope
- fix: add path parameters resolution for v2 api
- feat(console): upgrade toast-ui to 3.2.2
- fix(rest-api): improve getUserMember performance
- feat(console): remove Organization Theme settings
- fix: bump elasticsearch reporter and common lib to support ES8
- fix(portal-api): remove unnecessary apiService.findPublishedByUser
- fix: bump `@gravitee/ui-components` to `3.39.5`
- fix(console): use right env var to get settings.documentation url
</details>
[See all Jira …
> [APIM] Add changelog for new 3.20.9 release

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.25/pages/apim/3.x/changelog/changelog-3.18.adoc)
<details>
- fix: add path parameters resolution for v2 api
- fix(sdk): improve error logging and keyless policy
- feat(console): upgrade toast-ui to 3.2.2
- fix(rest-api): improve getUserMember performance
- fix(console): use right env var to get settings.documentation url
- fix: bump `@gravitee/ui-components` to `3.39.5`
- fix: remove requirement on repository CACHE type
- fix(portal-api): remove unnecessary apiService.findPublishedByUser
- fix: bump `gravitee-policy-cache` to `1.16.0`
</details>
[See all Jira issues for 3.18.x …
> [APIM] Add changelog for new 3.18.25 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.14/pages/apim/3.x/changelog/changelog-3.19.adoc)
<details>
- fix: remove requirement on repository CACHE scope
- fix: add path parameters resolution for v2 api
- feat(console): upgrade toast-ui to 3.2.2
- fix(rest-api): improve getUserMember performance
- fix: bump `@gravitee/ui-components` to `3.39.5`
- fix(console): use right env var to get settings.documentation url
- fix(portal-api): remove unnecessary apiService.findPublishedByUser
- fix: bump `gravitee-policy-cache` to `1.16.0`
</details>
[See all Jira issues for 3.19.x …
> [APIM] Add changelog for new 3.19.14 release

- pages/apim/3.x/installation-guide/upgrades/3.20.0/README.adoc
**Issue**
Add `JWT_MISSING_TOKEN` to the list of unusable response templates in APIM 3.20
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/add-missing-part-of-bc/index.html)
> Add `JWT_MISSING_TOKEN` to the list of unusable response templates in APIM 3.20

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.26/pages/apim/3.x/changelog/changelog-3.18.adoc)
<details>
- fix: remove closed plans in debug mode
- fix: set flowMode when convert DebugApi
- fix: apply the status filter when getting the list of applications
- fix: pagination data in applications
- feat(console): allow to search api to all the one accessible for the application subscription
- feat(rest-api): add `manageOnly` QueryParam to POST `_search/_paged`
- fix(design): resolve drag and drop on FF linux
- fix: enable use of API's metadata as email recipient
- fix: migrate all the fields of the API plans
- fix: resolve …
> [APIM] Add changelog for new 3.18.26 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.15/pages/apim/3.x/changelog/changelog-3.19.adoc)
<details>
- fix: remove closed plans in debug mode
- fix: set flowMode when convert DebugApi
- fix: resolve findAccessibleApiIdsForUser in ApiAuthorizationService
- fix: apply the status filter when getting the list of applications
- feat(console): allow to search api to all the one accessible for the application subscription
- feat(rest-api): add `manageOnly` QueryParam to POST `_search/_paged`
- fix: enable use of API's metadata as email recipient
- fix(design): resolve drag and drop on FF linux
- fix: pagination data in …
> [APIM] Add changelog for new 3.19.15 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.10/pages/apim/3.x/changelog/changelog-3.20.adoc)
<details>
- fix: remove closed plans in debug mode
- fix: set flowMode when convert DebugApi
- feat: support elasticsearch version 8
- fix: apply the status filter when getting the list of applications
- fix: resolve findAccessibleApiIdsForUser in ApiAuthorizationService
- feat(console): allow to search api to all the one accessible for the application subscription
- feat(rest-api): add `manageOnly` QueryParam to POST `_search/_paged`
- fix: enable use of API's metadata as email recipient
- fix(design): resolve drag and drop on FF …
> [APIM] Add changelog for new 3.20.10 release

- _config.yml
This PR bumps the version of AE 2.1.2
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/ae-2-1-2/index.html)
> fix: bump AE version to 2.1.2

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.27/pages/apim/3.x/changelog/changelog-3.18.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-18-27/index.html)
> [APIM] Add changelog for new 3.18.27 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.11/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-11/index.html)
> [APIM] Add changelog for new 3.20.11 release

- pages/apim/3.x/installation-guide/configuration/reporters/installation-guide-reporters.adoc
Add documentation for the Datadog reporter
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/datadog/index.html)
> feat: add documentation for the Datadog reporter

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.12/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-12/index.html)
> [APIM] Add changelog for new 3.20.12 release

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.28/pages/apim/3.x/changelog/changelog-3.18.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-18-28/index.html)
> [APIM] Add changelog for new 3.18.28 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.17/pages/apim/3.x/changelog/changelog-3.19.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-19-17/index.html)
> [APIM] Add changelog for new 3.19.17 release

- pages/apim/3.x/changelog/changelog-3.18.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.29/pages/apim/3.x/changelog/changelog-3.18.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-18-29/index.html)
> [APIM] Add changelog for new 3.18.29 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.18/pages/apim/3.x/changelog/changelog-3.19.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-19-18/index.html)
> [APIM] Add changelog for new 3.19.18 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.19/pages/apim/3.x/changelog/changelog-3.19.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-19-19/index.html)
> [APIM] Add changelog for new 3.19.19 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.14/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-14/index.html)
> [APIM] Add changelog for new 3.20.14 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.20/pages/apim/3.x/changelog/changelog-3.19.adoc)
> [APIM] Add changelog for new 3.19.20 release

- _config.yml
- _data/sidebars/am_3_x_sidebar.yml
- pages/am/3.x/breaking-changes/breaking-changes-4.0.adoc
- pages/am/3.x/breaking-changes/breaking-changes.adoc
- pages/am/3.x/installation-guide/installation-guide-migration.adoc
This PR update the documentation with AM 4.0 changes:
- fix(am): update AM version to 4.0.0
- fix(am): addition of migration note for 3.21 about MongoDB indexes
- docs: mention enterprise edition plugin in breaking changes
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-4-0-0/index.html)
> docs: add AM 4.0 changes

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.15/pages/apim/3.x/changelog/changelog-3.20.adoc)
> [APIM] Add changelog for new 3.20.15 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.16/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-16/index.html)
> [APIM] Add changelog for new 3.20.16 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.22/pages/apim/3.x/changelog/changelog-3.19.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-19-22/index.html)
> [APIM] Add changelog for new 3.19.22 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.18/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-18/index.html)
> [APIM] Add changelog for new 3.20.18 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.23/pages/apim/3.x/changelog/changelog-3.19.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-19-23/index.html)
> [APIM] Add changelog for new 3.19.23 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.19/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-19/index.html)
> [APIM] Add changelog for new 3.20.19 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.24/pages/apim/3.x/changelog/changelog-3.19.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-19-24/index.html)
> [APIM] Add changelog for new 3.19.24 release

- pages/apim/3.x/changelog/changelog-3.19.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.19.25/pages/apim/3.x/changelog/changelog-3.19.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-19-25/index.html)
> [APIM] Add changelog for new 3.19.25 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.20/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-20/index.html)
> [APIM] Add changelog for new 3.20.20 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.21/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-21/index.html)
> [APIM] Add changelog for new 3.20.21 release

- apim/3.x/management-api/3.20/swagger.json
**Issue**
https://gravitee.atlassian.net/browse/APIM-3091
https://github.com/gravitee-io/issues/issues/9351
Related to https://github.com/gravitee-io/gravitee-api-management/pull/5689
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/apim-3091-response-code/index.html)
> Change response code to 200 on closeApiPlan endpoint

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.22/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-22/index.html)
> [APIM] Add changelog for new 3.20.22 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.23/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-23/index.html)
> [APIM] Add changelog for new 3.20.23 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.24/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-24/index.html)
> [APIM] Add changelog for new 3.20.24 release

- pages/apim/3.x/installation-guide/red-hat/installation-guide-redhat-gateway.adoc
- pages/apim/3.x/installation-guide/red-hat/installation-guide-redhat-management-api.adoc
- pages/apim/3.x/installation-guide/red-hat/installation-guide-redhat-management-ui.adoc
- pages/apim/3.x/installation-guide/red-hat/installation-guide-redhat-portal.adoc
- pages/apim/3.x/installation-guide/red-hat/installation-guide-redhat-stack.adoc
**Issue**
https://gravitee.atlassian.net/browse/DV-96
https://gravitee.atlassian.net/browse/DV-246
* add the upgrade section in different part of installation process
* fix link to mongo installation and update it to version 7.0
* add new entry in changelog
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-dv-96-dv-246-rpm-install-upgrade-keep-config/index.html)
> feat: update doc and changelog about APIM upgrade installation on redhat

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.26/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-26/index.html)
> [APIM] Add changelog for new 3.20.26 release

- pages/apim/3.x/installation-guide/configuration/reporters/installation-guide-reporters.adoc
**Issue**
N/A
`Host` is not a valid configuration field for the datadog reporter.
> fix: remove non-existent configuration

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.27/pages/apim/3.x/changelog/changelog-3.20.adoc)
> [APIM] Add changelog for new 3.20.27 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.28/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-28/index.html)
> [APIM] Add changelog for new 3.20.28 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.29/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-29/index.html)
> [APIM] Add changelog for new 3.20.29 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.30/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-30/index.html)
> [APIM] Add changelog for new 3.20.30 release

- pages/apim/3.x/changelog/changelog-3.20.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.20.32/pages/apim/3.x/changelog/changelog-3.20.adoc)
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-apim-3-20-32/index.html)
> [APIM] Add changelog for new 3.20.32 release
