gravitee-io/gravitee-docs

pom.xml, src/main/asciidoc/docinfo.html, src/main/asciidoc/index-docinfo-footer.html, src/main/asciidoc/index-docinfo.html, src/main/asciidoc/index.adoc, src/main/asciidoc/installation-guide/installation-guide-docker.adoc, src/main/asciidoc/overview.adoc
=> feat(html): generate an html site looking like http://gravitee.io

Dockerfile, Jenkinsfile, pom.xml, src/main/assembly/distribution.xml
=> feat(docker): create a docker image

_data/sidebars/apim_sidebar.yml, pages/apim/user-guide/publisher/expression-language.adoc
=> doc(el): Add documentation about Gravitee.io Expression language

pages/apim/installation-guide/installation-guide-configuration.adoc
Thanks to review this PR.
Regards,
Alexandre.
=> Issue #425 : correct sharding tag example

_data/sidebars/apim_sidebar.yml, pages/apim/installation-guide/installation-guide-migration.adoc, pages/apim/installation-guide/installation-guide.adoc
=> doc(installation): Add a migration guide section

pages/apim/installation-guide/installation-guide-configuration.adoc, pages/apim/user-guide/publisher/publish-documentation.adoc
=> Add management of metadatas

pages/apim/installation-guide/installation-guide-configuration.adoc
=> feat(dynamodb): add dynamodb repository

pages/apim/installation-guide/installation-guide-management-webui.adoc
=> docs(installation): Update constants.json guide

pages/apim/quickstart/api-publisher.adoc
=> Documentation typo

_data/sidebars/apim_sidebar.yml, pages/apim/installation-guide/installation-guide-repositories-elasticsearch.adoc, pages/apim/installation-guide/installation-guide-repositories-mongodb.adoc
=> doc(elasticsearch): Moving from ES 2.x to 5.x

pages/apim/installation-guide/installation-guide-portal-configuration.adoc
=> docs(portal): Customize footer links

pages/apim/installation-guide/installation-guide-management-api-configuration.adoc
=> Added the 'subscriptionUrl' variable to the 'subscriptionRejected.html' mail template

pages/apim/installation-guide/installation-guide-portal-configuration.adoc
=> docs(constants): Update constants.json

pages/apim/installation-guide/installation-guide-management-api-configuration.adoc
=> Add the user variable on the email of user registration

pages/apim/installation-guide/installation-guide-management-api-configuration.adoc
=> Display expiration date on revocation's email

pages/apim/installation-guide/installation-guide-management-api-configuration.adoc, pages/apim/installation-guide/installation-guide-portal-configuration.adoc
=> Contact screen to send an email to the support team

pages/apim/installation-guide/installation-guide-management-api-configuration.adoc, pages/apim/user-guide/publisher/api-rating.adoc
Closes  gravitee-io/issues#840
=> Implementation of rating of APIs

pages/apim/installation-guide/installation-guide-management-api-configuration.adoc
https://github.com/gravitee-io/gravitee-management-rest-api/pull/311
=> Add about JsonPath documentation

pages/apim/installation-guide/installation-guide-management-api-configuration.adoc
=> feat(notifications): add user notifications

pages/apim/installation-guide/installation-guide-repositories-jdbc.adoc, pages/apim/installation-guide/installation-guide-repositories.adoc
This closes gravitee-io/issues#344
=> feat: implementation of JDBC repository for version 1.14

pages/apim/installation-guide/installation-guide-management-api-configuration.adoc
=> feat(subscription): add a reason on accept and on request

pages/apim/installation-guide/installation-guide-repositories-jdbc.adoc
This closes gravitee-io/issues#1212
=> feat: Add support for MariaDB

pages/apim/installation-guide/installation-guide-management-api-configuration.adoc
=> feat(jetty): enable https only mode

pages/apim/installation-guide/partial/how-to-configure.adoc
fix gravitee-io/gravitee-docs#91
=> fix(configuration): explain how to configure array of values with envvar

pages/am/2.x/breaking-changes/breaking-changes-2.0.adoc, pages/am/2.x/quickstart/profile-information.adoc, pages/am/2.x/user-guide/identity-provider/user-guide-mapping-identity-provider.adoc
=> feat(am): update OpenID Connect new base path endpoint information

_data/sidebars/am_2_x_sidebar.yml, am/2.x/oauth2/index.html, am/2.x/oauth2/swagger.yml, am/2.x/oidc/index.html, am/2.x/oidc/swagger.yml, index.adoc, pages/am/2.x/protocols/oauth2/overview.adoc, pages/am/2.x/protocols/oidc/overview.adoc, pages/am/2.x/protocols/protocols-overview.adoc
=> feat(am): add OAuth 2.0 and OpenID Connect documentation

pages/apim/installation-guide/installation-guide-docker.adoc
As reported in https://github.com/gravitee-io/issues/issues/1734
=> Elasticsearch vm.max_map_count property fix

pages/apim/installation-guide/partial/how-to-configure.adoc
Closes gravitee-io/issues#1809
=> fix(envvar): Add warning about case sensitivity.

pages/apim/installation-guide/partial/how-to-configure.adoc
=> fix(config): how to deal with hyphens

pages/apim/installation-guide/installation-guide-management-api-configuration.adoc
=> feat(ldap): add new configuration to search for users

pages/apim/installation-guide/installation-guide-repositories-jdbc.adoc
This closes gravitee-io/issues#1772
=> Add SqlServer support

pages/apim/installation-guide/installation-guide-gateway-configuration.adoc
Closes gravitee-io/issues#1834
=> feat(http): Update gateway configuration

404.md, pages/apim/installation-guide/installation-guide-management-api-security.adoc, pages/node/partial/security.adoc
this closes gravitee-io/issues#2117 and is related to gravitee-io/gravitee-management-rest-api#656
=> add gravitee fail2ban article

pages/am/2.x/protocols/oidc/overview.adoc
Linked to Graivtee Access Management [PR 555](https://github.com/gravitee-io/graviteeio-access-management/pull/555)
=> Add documentation on update endpoint of Openid Connect DCR feature

pages/am/2.x/user-guide/certificate/user-guide-create-certificate.adoc
This come with [Gravitee AM PR](https://github.com/gravitee-io/graviteeio-access-management/pull/560)
=> Specify how to generate RS512 key

_data/sidebars/apim_sidebar.yml, pages/apim/user-guide/publisher/policies/policy-role-based-access-control.adoc
=> feat(rbac): Add Role-BAsed Access Control policy

pages/am/2.x/user-guide/client/user-guide-dynamic-client-registration.adoc
this is related to issue [#2297](https://github.com/gravitee-io/issues/issues/2297)
=> redirect_uri is not always required

am/2.x/oidc/swagger.yml, pages/am/2.x/user-guide/client/user-guide-dynamic-client-registration.adoc
This fix issue [#2323](https://github.com/gravitee-io/issues/issues/2323)
Please Merge this PR at the same time that this [PR](https://github.com/gravitee-io/graviteeio-access-management/pull/591).
=> Renew client_secret through dcr

pages/am/2.x/user-guide/client/user-guide-dynamic-client-registration.adoc
This is related to issue [#2326](https://github.com/gravitee-io/issues/issues/2326) and should be merged with this [Pull Request](https://github.com/gravitee-io/graviteeio-access-management/pull/605)
=> DCR scope management documentation

pages/am/2.x/installation-guide/installation-guide-configuration.adoc
Fixes a broken management api configuration anchor.
=> doc(installation-guide): update mgt api conf link

pages/apim/user-guide/admin/admin-guide-roles-and-permissions.adoc
=> Typo in Scope section

pages/am/2.x/installation-guide/installation-guide-configuration.adoc
Previous link no longer valid.
=> Updated MongoDB Client Options Reference URL

pages/am/2.x/installation-guide/installation-guide-management-api.adoc
Added how to load balance using Apache httpd with additional cookies.
=> Add information on Load Balancing.

pages/am/2.x/user-guide/client/user-guide-dynamic-client-registration.adoc
Completed word and added better explanation in Client Secret renew.
=> Typo and better explanation

pages/am/2.x/user-guide/user-management/registration/user-guide-registration.adoc
In AM user registration page, `Custom form` link was broken. Updated link accordingly.
=> Update `Custom forms` link

pages/am/2.x/installation-guide/installation-guide-gateway-install-rpm.adoc, pages/am/2.x/installation-guide/installation-guide-management-api-install-rpm.adoc, pages/am/2.x/installation-guide/installation-guide-management-ui-install-rpm.adoc, pages/apim/1.x/installation-guide/installation-guide-docker_compose.adoc, pages/apim/1.x/installation-guide/installation-guide-docker_customize.adoc, pages/apim/1.x/installation-guide/installation-guide-gateway-install-rpm.adoc, pages/apim/1.x/installation-guide/installation-guide-management-api-install-rpm.adoc, pages/apim/1.x/installation-guide/installation-guide-portal-install-rpm.adoc
Closes gravitee-io/issues#3351
=> doc: Update docker compose for API Management

pages/apim/1.x/installation-guide/installation-guide-repositories-elasticsearch.adoc
Fix settings for connect to Elasticsearch. 
https://github.com/gravitee-io/issues/issues/3589
=> FIX issue #3589

_data/sidebars/am_3_x_sidebar.yml, am/current/uma2/index.html, am/current/uma2/swagger.yml, pages/am/3.x/protocols/protocols-overview.adoc, pages/am/3.x/protocols/uma2/overview.adoc
Closes gravitee-io/issues#4009
=> feat(am): add UMA 2.0 functional documentation

pages/apim/1.x/installation-guide/installation-guide-gateway-configuration.adoc
=> feat: Allows to configure custom regexes on the user agent processor

pages/apim/1.x/user-guide/publisher/publish-documentation.adoc
=> fix(docs): fix heading type

pages/apim/1.x/user-guide/admin/admin-guide-roles-and-permissions.adoc, pages/apim/3.x/user-guide/admin/admin-guide-roles-and-permissions.adoc
=> fix: add tips about GROUP permission

pages/apim/1.x/user-guide/admin/admin-guide-roles-and-permissions.adoc, pages/apim/3.x/user-guide/admin/admin-guide-roles-and-permissions.adoc
=> fix(management): set user authorities within userDetails object

pages/apim/3.x/installation-guide/repositories/installation-guide-repositories-mongodb.adoc
Closes gravitee-io/issues#4335
=> docs(): add precision on mongo supported version

pages/apim/3.x/dev-guide/dev-guide-boostrap.adoc
Fixes #https://github.com/gravitee-io/issues/issues/4371
=> docs: improve documentation for installation guide

pages/apim/1.x/installation-guide/installation-guide-management-api-configuration.adoc, pages/apim/3.x/installation-guide/rest-apis/installation-guide-rest-apis-configuration.adoc
=> fix(management): #4100 addition of a ttl for gateways in unknown state

pages/am/3.x/installation-guide/amazon-linux/installation-guide-amazon-stack.adoc, pages/am/3.x/installation-guide/red-hat/installation-guide-redhat-stack.adoc, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-stack.adoc, pages/apim/3.x/installation-guide/red-hat/installation-guide-redhat-stack.adoc
Replaced incorrect with-dependencies install commands following discussion with Rory and David for both APIM and AM.
=> Updated with dependencies command

pages/apim/3.x/user-guide/publisher/expression-language.adoc
Closes gravitee-io/issues#4431
=> feat(processor): add path parameters processing

pages/am/3.x/breaking-changes/breaking-changes-3.4.adoc, pages/am/3.x/installation-guide/installation-guide-migration.adoc
=> docs(session): migration guide related to AM cookie session management

pages/apim/3.x/installation-guide/configuration/gateway/installation-guide-gateway-configuration.adoc
Fixes https://github.com/gravitee-io/issues/issues/4434
=> feat: forward x-forwarded-prefix to the backend endpoint

pages/apim/3.x/installation-guide/configuration/management-ui/installation-guide-management-ui-configuration.adoc
Fixes https://github.com/gravitee-io/issues/issues/4458
=> feat: allow to define background color of login page

pages/apim/3.x/installation-guide/configuration/rest-apis/installation-guide-rest-apis-configuration.adoc
=> feat: override settings via envvars

pages/am/3.x/installation-guide/installation-guide-repositories-jdbc.adoc, pages/am/3.x/user-guide/identity-provider/userguide-database-identity-provider-jdbc.adoc
=> feat(JDBC/IDP): create default IDP

pages/am/3.x/installation-guide/installation-guide-repositories-jdbc.adoc
=> feat(reporter-jdbc): addition of JDBC reporter note

pages/apim/3.x/installation-guide/authentication/installation-guide-authentication-inmemory.adoc, pages/apim/3.x/installation-guide/authentication/installation-guide-authentication.adoc
=> feat(authent): how to generate a bcrypt password

pages/am/3.x/installation-guide/installation-guide-repositories-jdbc.adoc
=> feat(am-jdbc): addition of purge scheduled task

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/breaking-changes/breaking-changes-3.5.adoc, pages/am/3.x/overview/concepts.adoc
closes gravitee-io/issues#4820
=> am: remove extension point policiy endpoints for the flow endpoints

pages/apim/3.x/installation-guide/installation_guide_hybrid_deployment.adoc
Closes gravitee-io/issues#4885
=> feat(bridge-http): MTLS support

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/policy-reference/policy-assign-metrics.adoc
Closes gravitee-io/issues#4769
=> feat: new assign-metrics policy

_data/sidebars/ae_sidebar.yml, pages/ae/installation-guide/installation-guide-configuration.adoc, pages/ae/installation-guide/installation-guide-migration.adoc
=> docs(ae): add AE upgrade instructions

pages/apim/3.x/installation-guide/authentication/installation-guide-authentication-keycloak.adoc
See https://github.com/gravitee-io/issues/issues/4957
=> [#4957] fix missing images on keycloak apim page

pages/apim/3.x/installation-guide/docker/installation-guide-docker_compose.adoc
=> Fixed missing Docker config for remote install

Gemfile, _data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/policy-reference/policy-json-xml.adoc
=> feat: add documentation for Json to xml policy

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/policy-reference/policy-data-logging-masking.adoc
=> feat(management): add data logging masking policy

pages/am/3.x/admin-guide/admin-guide-organizations-and-environments.adoc
=> doc(AM/Cockpit): remove notion of EE for AM and Cockpit

pages/apim/3.x/installation-guide/configuration/authentication/installation-guide-authentication-graviteeam.adoc, pages/apim/3.x/installation-guide/configuration/authentication/installation-guide-authentication-keycloak.adoc
Closes gravitee-io/issues#4803
=> docs: change gravitee.yml examples for roleMappings

_data/sidebars/am_3_x_sidebar.yml, css/customstyles.css, pages/am/3.x/user-guide/identity-provider/enterprise/user-guide-enterprise-identity-providers.adoc, pages/am/3.x/user-guide/identity-provider/enterprise/userguide-enterprise-identity-provider-kerberos.adoc
=> am: add Kerberos IdP documentation

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/user-guide/publisher/plans-subscriptions.adoc, pages/apim/3.x/user-guide/publisher/resources/resources-overview.adoc
See also https://github.com/gravitee-io/gravitee-policy-basic-authentication/pull/3
=> Basic authentication doc

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/user-guide/user-management/consent/user-guide-consent.adoc, pages/am/3.x/user-guide/user-management/password/user-guide-password-policy.adoc
=> am: add password policy section

_data/sidebars/ae_sidebar.yml, _data/sidebars/am_3_x_sidebar.yml, pages/ae/am/am-configuration.adoc, pages/ae/am/am-installation.adoc, pages/am/3.x/user-guide/alerts/user-guide-alerts-ae.adoc, pages/am/3.x/user-guide/alerts/user-guide-alerts-notifications-email.adoc, pages/am/3.x/user-guide/alerts/user-guide-alerts-notifications-partial.adoc, pages/am/3.x/user-guide/alerts/user-guide-alerts-notifications-slack.adoc, pages/am/3.x/user-guide/alerts/user-guide-alerts-notifications-webhook.adoc, pages/am/3.x/user-guide/alerts/user-guide-alerts-notifications.adoc, pages/am/3.x/user-guide/alerts/user-guide-alerts-overview.adoc, pages/am/3.x/user-guide/alerts/user-guide-alerts.adoc
=> am: add alerts section

css/customstyles.css, pages/am/3.x/user-guide/identity-provider/enterprise/userguide-enterprise-identity-provider-cas.adoc, pages/am/3.x/user-guide/identity-provider/enterprise/userguide-enterprise-identity-provider-saml2.adoc
=> am: add SAML SP metadata endpoint note

pages/apim/3.x/installation-guide/configuration/gateway/installation-guide-gateway-configuration.adoc, pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-jdbc.adoc, pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-mongodb.adoc
=> feat: allows to define a prefix for collections / tables

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/installation-guide/configuration/installation-guide-cache.adoc
=> docs(apim): add documentation about cache configuration

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/policy-reference/policy-traffic-shadowing.adoc, pages/apim/3.x/user-guide/publisher/backend-services.adoc
Fixes https://github.com/gravitee-io/issues/issues/5186
=> feat: traffic shadowing

pages/node/partial/technical-api.adoc
=> feat: allow to detect when the gateway is up vs when it is ready

pages/apim/3.x/user-guide/publisher/create-api.adoc, pages/apim/3.x/user-guide/publisher/plans-subscriptions.adoc
Closes gravitee-io/issues#1553
=> doc: rename path authorization to resource filtering

pages/apim/3.x/user-guide/admin/admin-guide-roles-and-permissions.adoc
Fixes https://github.com/gravitee-io/issues/issues/5396
=> feat: associate sharding tags and tenants to organization

pages/apim/3.x/installation-guide/configuration/gateway/installation-guide-gateway-configuration.adoc
Fixes https://github.com/gravitee-io/issues/issues/5357
=> feat: allow to associate a gateway to environments

_data/sidebars/cockpit_sidebar.yml, index.adoc, pages/cockpit/installation-guide/configuration/configuration-guide.adoc, pages/cockpit/installation-guide/configuration/repositories/installation-guide-repositories-jdbc.adoc
https://github.com/gravitee-io/gravitee-cockpit/issues/172
=> feat(cockpit): jdbc installation guide

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/breaking-changes/breaking-changes-3.9.adoc, pages/am/3.x/breaking-changes/breaking-changes.adoc, pages/am/3.x/installation-guide/installation-guide-migration.adoc
=> [AM] add breaking changes notes

pages/ae/user-guide/user-guide-conditions.adoc, pages/ae/user-guide/user-guide-notifier-message.adoc
Linked with gravitee-io/issues#5481
=> feat(management): allow to customize consumer alerts

pages/node/partial/technical-api.adoc
Fixes https://github.com/gravitee-io/issues/issues/5236
=> feat: allow to filter probes on health resource

pages/node/partial/technical-api.adoc
Fixes https://github.com/gravitee-io/issues/issues/4903
⚠️🛑
Need to be merged after https://github.com/gravitee-io/issues/issues/5236
=> feat: resource information in health API

pages/apim/3.x/installation-guide/configuration/rest-apis/installation-guide-rest-apis-configuration.adoc
=> fix(management): clean CORS env vars & migration guide

pages/apim/3.x/kubernetes/apim-kubernetes-admission-hook.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-installation.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-quick-start.adoc
Fix links about kubernetes plugin
=> fix(kubernetes): fix download link

pages/apim/3.x/user-guide/publisher/backend-services.adoc
https://github.com/gravitee-io/issues/issues/4943
=> feat: allow to use EL in health check configuration

pages/am/3.x/user-guide/flows/user-guide-policies-extension-points.adoc
=> feat: add flow creation and enable flow condition

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/breaking-changes/breaking-changes-3.10.adoc, pages/am/3.x/breaking-changes/breaking-changes.adoc, pages/am/3.x/installation-guide/installation-guide-migration.adoc
=> chore: remove deprecated endpoints

pages/am/3.x/installation-guide/configuration/installation-guide-repositories-mongodb.adoc
=> chore(mongo): Update MongoDB driver

pages/apim/3.x/installation-guide/red-hat/installation-guide-redhat-management-api.adoc
changed management-api to rest-api to match installation
=> update yum install doc for management-api

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/installation-guide/configuration/installation-guide-cache.adoc, pages/apim/3.x/user-guide/publisher/resources/resource-cache-redis.adoc
=> feat(management): add support Redis for cache resource

pages/am/3.x/installation-guide/installation-guide-migration.adoc
=> fix: add note about AE for Gravitee AM EE

pages/apim/3.x/installation-guide/configuration/installation-guide-cache.adoc
Related to gravitee-io/issues#5671
=> docs(cache): improve doc on hazelcast cache

_data/sidebars/cockpit_sidebar.yml, index.adoc, pages/cockpit/installation-guide/configuration/configuration-guide.adoc, pages/cockpit/installation-guide/configuration/idp/installation-guide-idp-generic-oauth2.adoc, pages/cockpit/installation-guide/configuration/repositories/installation-guide-repositories-jdbc.adoc, pages/cockpit/installation-guide/installation-guide-configuration.adoc, pages/cockpit/installation-guide/installation-guide-docker-images.adoc, pages/cockpit/installation-guide/installation-guide-introduction.adoc, pages/cockpit/installation-guide/installation-guide-kubernetes.adoc, pages/cockpit/installation-guide/zip/installation-guide-management-api-install-zip.adoc, pages/cockpit/installation-guide/zip/installation-guide-management-ui-install-zip.adoc
Merge cockpit on-prem doc on develop to make it available on nightly-docs.gravitee.io
=> Cockpit on premise

pages/am/3.x/breaking-changes/breaking-changes-3.10.adoc, pages/am/3.x/installation-guide/installation-guide-migration.adoc
=> feat: split users collection

pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-mongodb.adoc
update gravitee.yml default configuration for mongo database
gravitee-io/issues#3661
=> doc: upgrade mongo-driver

.github/CODEOWNERS, .github/pull_request_template.md, Gemfile, Gemfile.lock, README.adoc
**Issue**
NA
- Give ownership of this repo to @gravitee-io/tech-writer
- Add a simple Pull Request template
- Complete README section about how to start documentation locally
=> GitHub setup

pages/apim/3.x/user-guide/publisher/promote-api.adoc
issue
https://github.com/gravitee-io/issues/issues/5921
=> docs: API promotion documentaiton

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/installation-guide/installation-guide.adoc
**Issue**
No official ticket for this pull request. 
Fixed broken links in Installation Guide, removed Quick Installation page from nav menu (broken link), made nav menu edits. 
I am updating the installation guide (along with ALL of our tech content) based on conversations I've had with Chris, Elesh, Ami & Gaetan.
=> fixed links & nav menu

pages/apim/3.x/installation-guide/installation-guide.adoc
Fixed links on Installation Guide Introduction page.
=> updated links

pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-stack.adoc, pages/apim/3.x/installation-guide/installation-guide.adoc
Made additional updates to Introduction page and Amazon Install Full APIM Stack page.
=> More updates

.circleci/config.yml, _data/sidebars/apim_1_x_sidebar.yml, _data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-stack.adoc, pages/apim/3.x/installation-guide/installation-guide.adoc
Made improvements to installation guide & nav menu.
=> Install Guide Updates

_data/sidebars/apim_3_x_sidebar.yml
=> more nav menu updates

pages/apim/3.x/installation-guide/installation-guide.adoc
Fixing VSCode formatting on develop branch
=> fixing VSCode formatting

_data/sidebars/apim_1_x_sidebar.yml, _data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/installation-guide/installation-guide.adoc, pages/apim/3.x/overview/architecture.adoc, pages/apim/3.x/overview/concepts.adoc, pages/apim/3.x/overview/introduction.adoc
Streamlining docs by combining/editing related pages.
=> Combined intro & concepts pages

pages/cockpit/installation-guide/installation-guide-configuration.adoc
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/540
Change config name for data purge
=> feat: change config name for cockpit data purge

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/dev-guide/dev-guide-boostrap.adoc, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-introduction.adoc, pages/apim/3.x/installation-guide/docker/installation-guide-docker_images.adoc
Updated some of the Amazon install guide (renamed `yum` page), the Docker images guide, and the Dev guide for bootstrapping your env.
=> updating install guides

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-configure-yum.adoc
Fixing minor problem with page.
=> fixing nav menu

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/quickstart/quickstart-overview.adoc
Moved Install Guides to be listed before the QSG section.
=> nav menu edits

pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-mongodb.adoc
add precision on the APIM <-> mongo server compatibility
Before:
After:
=> doc: add precision on the APIM <-> mongo server compatibility

pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-stack.adoc, pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-mongodb.adoc
Dropped commit change and closed unnecessary PR.
=> APIM MongoDB Chart Improvement 

pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-configure-yum.adoc, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-stack.adoc, pages/apim/3.x/overview/architecture.adoc
updating overview, architecture, and addtl copy edits.
=> updating overview

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-stack.adoc
1. Updated sidebar nav menu to include production-ready env configuration in Install Guides. 
2. Removed How To intro page (will probably delete and reorganize the entire section). 
3. Edited & updated written tech copy on AWS Linux install guide.
=> edited AWS install

pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-configure-yum.adoc, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-gateway.adoc, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-management-api.adoc, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-management-ui.adoc, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-portal.adoc, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-stack.adoc, pages/apim/3.x/installation-guide/docker/installation-guide-docker_compose.adoc, pages/apim/3.x/installation-guide/docker/installation-guide-docker_images.adoc
Edited all Amazon install guides.
=> Edited All Amazon Guides

pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-gateway.adoc, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-management-api.adoc
Additional Amazon install guide edits.
=> New edits 496

pages/apim/3.x/installation-guide/installation-guide.adoc
fixing broken link on Amazon Install page (redirecting to Configure YUM page now).
=> Fixing Amazon Intro Page Broken Link

pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-redis.adoc
=> docs: enhance documentation for rate limiting with redis

_includes/footer.html, _layouts/redirected.html, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-introduction, pages/privacypolicy/site-privacy-policy.adoc
=> Fixing 404 Broken Link

_includes/footer.html, _layouts/redirected.html, pages/apim/3.x/installation-guide/amazon-linux/installation-guide-amazon-introduction, pages/privacypolicy/site-privacy-policy.adoc
Added privacy policy to site (as a hidden page not listed on the nav menu) and added hyperlink to site footer.
=> adding privacy policy

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/policy-reference/policy-javascript.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/5948
Add a new javascript policy.
=> feat(javascript): add documentation about javascript policy

pages/apim/3.x/dev-guide/dev-guide-boostrap.adoc, pages/apim/3.x/installation-guide/configuration/rest-apis/installation-guide-rest-apis-configuration.adoc, pages/apim/3.x/installation-guide/with-zip/installation-guide-rest-apis-install-zip.adoc, pages/apim/3.x/user-guide/publisher/create-api.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/5900
renaming zipfile and folder name dur to APIM refactoring
=> docs: renaming zipfile and folder name dur to APIM refactoring

_includes/GoogleTagManager_body.liquid, _includes/GoogleTagManager_head.liquid, _layouts/api.html, _layouts/default.html, _layouts/default_print.html, _layouts/homepage.html
Adding new google tag to all pages (head & body) and updated existing google analytics info (moved to body section).
=> Adding new google tag

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/policy-reference/policy-generate-http-signature.adoc
=> docs: add generate http signature policy documentation

_config.yml, _data/sidebars/cockpit_sidebar.yml, _data/topnav.yml, index.adoc, pages/apim/3.x/user-guide/publisher/promote-api.adoc, pages/cockpit/changelog.adoc, pages/cockpit/installation-guide/configuration/configuration-guide.adoc, pages/cockpit/installation-guide/configuration/idp/installation-guide-idp-generic-oauth2.adoc, pages/cockpit/installation-guide/configuration/idp/installation-guide-idp-github.adoc, pages/cockpit/installation-guide/configuration/idp/installation-guide-idp-google.adoc, pages/cockpit/installation-guide/configuration/repositories/installation-guide-repositories-jdbc.adoc, pages/cockpit/installation-guide/installation-guide-configuration.adoc, pages/cockpit/installation-guide/installation-guide-docker-images.adoc, pages/cockpit/installation-guide/installation-guide-introduction.adoc, pages/cockpit/installation-guide/installation-guide-kubernetes.adoc, pages/cockpit/installation-guide/installation-guide-migration.adoc, pages/cockpit/installation-guide/zip/installation-guide-management-api-install-zip.adoc, pages/cockpit/installation-guide/zip/installation-guide-management-ui-install-zip.adoc, pages/cockpit/overview/compatibility.adoc, pages/cockpit/overview/introduction.adoc, pages/cockpit/quick-start/get-started.adoc, pages/cockpit/user-guide/installation-health-check.adoc, pages/cockpit/user-guide/register-installations.adoc
**Issue**
N.A 
Add Cockpit changelog and migration guides
=> Cockpit changelog

pages/apim/3.x/installation-guide/configuration/gateway/opentracing-in-docker.adoc
Included link and reworded for technical accuracy.
=> More OpenTracing Edits

pages/apim/3.x/installation-guide/installation-guide-kubernetes.adoc
Updated Helm chart to include PostgresSQL details (as an alternative to MongoDB); also updated entire guide, but more edits for quality still need to be made.
=> Update Helm Chart

pages/am/3.x/breaking-changes/breaking-changes-3.4.adoc
=> doc: update breaking changes guide for AM 3.4

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/installation-guide/installation-guide-production-ready.adoc
closes gravitee-io/issues#6106
=> am: add configure production-ready AM environment page

_data/sidebars/am_3_x_sidebar.yml, _data/sidebars/apim_3_x_sidebar.yml
Readding nav menu that was accidentally deleted.
=> Readding nav-menu

pages/apim/3.x/user-guide/publisher/expression-language.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/5322
Update the Expression Language documentation with new entries about SSL Session
...
=> feat: allow access to SSL attributes in EL TemplateEngine

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/breaking-changes/breaking-changes-3.10.4.adoc, pages/am/3.x/breaking-changes/breaking-changes.adoc, pages/am/3.x/installation-guide/installation-guide-migration.adoc
=> doc(am): add migration note for AM 3.10.4 about JWK

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/breaking-changes/breaking-changes-3.12.adoc, pages/am/3.x/breaking-changes/breaking-changes.adoc
=> docs: Breaking changes on AM REST API about application scopes

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/breaking-changes/breaking-changes-3.12.adoc, pages/am/3.x/dev-guide/protocols/fapi/overview.adoc, pages/am/3.x/dev-guide/protocols/protocols-overview.adoc
=> doc: add FAPI as protocol and provide some input on how to configure it

_data/sidebars/apim_3_x_sidebar.yml, pages/am/3.x/user-guide/mfa/user-guide-mfa-amfa.adoc
=> doc: add warning about heap size when GeoIp plugin is deployed

Dockerfile, Dockerfile-build
We have updated the FROM image to `ruby:2.7-slim-bullseye` and `nginx:1.21-alpine` to improve security.
Additionally, I have made the Jeykll version a build-stage variable and pumped the version to `4.2.1`.
=> Change FROM image in Dockerfiles

pages/apim/3.x/user-guide/publisher/response-templates.adoc
=> doc: customize http signature response template

pages/apim/3.x/api-reference/rest-apis-documentation.adoc
Spec versions updated
**Issue**
N/A
Changed the API reference so that it always shows the most up to date version.
This was reported by a customer and passed on through Slack
=> API ref version update

pages/apim/3.x/installation-guide/configuration/management-ui/installation-guide-management-ui-configuration.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/6365
=> 6365 api status dashboard

pages/am/3.x/user-guide/mfa/user-guide-mfa-amfa.adoc
relates to closed PR https://github.com/gravitee-io/gravitee-docs/pull/589
Updating the docs for geoip plugin
=> docs: geoip docs update

_config.yml
APIM 3.12.2 has been released on 2021-11-12
=> doc: update latest version of APIM

pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-elasticsearch.adoc
https://github.com/gravitee-io/issues/issues/6507
Some documentation improvement suggestion ;
I think we have to add some notes about how to manage your indexes with ILM,
Explaining how to configure dates suffixes.
=> docs: add notes about how to manage elasticSearch indexes with ILM

pages/cockpit/changelog.adoc
**Issue**
N.A.
Update Cockpit changelog up to 3.14
=> feat: update Cockpit changelog

_config.yml
Update the latest version of APIM: 3.12.3
=> doc: release APIM 3.12.3

pages/ae/installation-guide/installation-guide-docker.adoc, pages/am/3.x/installation-guide/docker/installation-guide-docker-images.adoc, pages/apim/3.x/installation-guide/docker/installation-guide-docker_images.adoc, pages/cockpit/installation-guide/installation-guide-docker-images.adoc, pages/ee/installation-guide/installation-guide-docker.adoc
The goal of this PR is to update the docker base images of our products.
@gravitee-io/cockpit ✅
@gravitee-io/am✅
@gravitee-io/apim ✅ 
@gravitee-io/architecture 
please check the current PR and fix or complete what is needed.
=> Update docker base image version

pages/privacypolicy/site-privacy-policy.adoc
**Issue**
Updated privacy policy
=> New privacy policy

pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-elasticsearch.adoc
https://github.com/gravitee-io/issues/issues/6423
=> docs: add OpenSearch in supported ElasticSearch versions list

pages/ee/overview/version.adoc
I'm updating the website to reflect current versions
=> added latest APIM versions

pages/cockpit/installation-guide/installation-guide-docker-images.adoc, pages/cockpit/installation-guide/zip/installation-guide-management-api-install-zip.adoc
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/1402
Add license usage examples for cockpit installation.
=> docs: add license usage for cockpit

pages/cockpit/installation-guide/configuration/idp/installation-guide-idp-generic-oauth2.adoc, pages/cockpit/installation-guide/configuration/idp/installation-guide-idp-github.adoc, pages/cockpit/installation-guide/configuration/idp/installation-guide-idp-google.adoc
Describe how to disable the idp plugins on cockpit.
=> docs: add how to disable an idp environment variable for cockpit

_data/sidebars/cockpit_sidebar.yml, pages/cockpit/user-guide/api-designer.adoc
**Issue**
https://github.com/gravitee-io/gravitee-docs/issues/528
API Designer doc
=> Cockpit api designer

_config.yml
=> doc: release APIM 3.13.2

pages/am/3.x/user-guide/mfa/user-guide-mfa-factors.adoc, pages/am/3.x/user-guide/resources/user-guide-resources-smtp.adoc
fixes issues/#628
fix a broken link and complete content of SMTP resource page
=> doc(am): fix broken link and complete SMTP resource page description

pages/apim/3.x/user-guide/publisher/expression-language.adoc
docs: in expression language page, add node attributes list
=> docs: in expression language page, add node attributes list

pages/apim/3.x/quickstart/api-publisher/api-publisher-api.adoc
**Issue**
https://github.com/gravitee-io/gravitee-docs/issues/619
Fixing a typo
=> docs: fix typo on quickstart

pages/apim/3.x/installation-guide/configuration/gateway/installation-guide-gateway-configuration.adoc
Fix wrong configuration example.
=> fix: fix wrong configuration example for certificate reloading

pages/apim/3.x/user-guide/publisher/sme/using-kafka-controller.adoc
Fix a sidebar link and an url leading to our internal servers.
=> Fix link and snippet url

pages/am/3.x/user-guide/identity-provider/corporate/userguide-enterprise-identity-provider-saml2.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/6835
Added documentation on assertion encryption
❌ 
https://github.com/gravitee-io/gravitee-access-management/pull/1625
https://github.com/gravitee-io/gravitee-am-identityprovider-saml/pull/24
=> docs: SAML2.0 encryption documentation

_config.yml
=> APIM 3.15.1 has been released

pages/cockpit/changelog.adoc
**Issue**
N.A. 
Add changelog for Cockpit 3.15
=> feat(cockpit): changelog

pages/cockpit/changelog.adoc
**Issue**
N.A.
Cockpit 3.16 change log
=> feat: Cockpit 3.16 changelog

pages/apim/3.x/quickstart/api-consumer/api-consumer-api.adoc
**Issue**
https://github.com/gravitee-io/gravitee-docs/issues/620
Fixed example as described in the issue, @mouligno needs to check the new example to confirm that it works.
=> Issue620 incorrect example

pages/apim/3.x/policy-reference/policy-javascript.adoc
Rewrote Javascript Policy documentation to include as much detail as possible.
=> rewrote Javascript Policy documentation

.circleci/config.yml
Adding a scheduled workflow to remove containers older than 30days from AzureStorage.
Every Sunday at 5:00am, a job will be launched and will:
- list all containers
- for each one, get the first file
- check if the lastModified date of the file is older that 30days ago
- if true, the container is deleted.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/purge-azure-storage-container/index.html)
=> Purge old containers from Azure storage

pages/apim/3.x/installation-guide/installation-guide-plugins.adoc
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-64?atlOrigin=eyJpIjoiYzFiODlkNmRjNmQzNGM1ODgzMzMyYTk4NzEwZjYzNzciLCJwIjoiamlyYS1zbGFjay1pbnQifQ
Provided information on adding plugins to APIM
=> Doc 64 plugins documentation

pages/apim/3.x/user-guide/publisher/create-api.adoc, pages/apim/3.x/user-guide/publisher/import-apis.adoc
https://github.com/gravitee-io/issues/issues/7003
https://github.com/gravitee-io/issues/issues/7013
=> docs(apim): initialize API import documentation

pages/apim/3.x/policy-reference/policy-javascript.adoc, pages/apim/3.x/user-guide/publisher/sme/introducing-kafka.adoc
Replace one absolute link  by a relative one.
Change syntax to generate relative links for other links.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-links/index.html)
=> Fixing relative links

pages/apim/3.x/policy-reference/policy-javascript.adoc, pages/apim/3.x/user-guide/publisher/create-api.adoc, pages/apim/3.x/user-guide/publisher/import-apis.adoc
fix relatives URL in links
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-relative-links/index.html)
=> fix relatives URL in links

pages/node/partial/metrics.adoc
**Issue**
Na
Merge 3.10.11 stuff into master
=> Apim release 3.10.11

.circleci/config.yml
=> fix: syntax error 🤦🏻‍♂️ in bash command

pages/apim/3.x/dev-guide/dev-guide-boostrap.adoc
Rewrite the developer guide page according to the APIM monorepo
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/update-apim-developer-guide/index.html)
=> docs: rewrite the developer guide page according to the APIM monorepo

pages/apim/3.x/user-guide/publisher/design-studio/design-studio-create.adoc
**Issue**
NA
Merge doc of APIM 3.10.12 in master
=> Merge doc of APIM 3.10.12 in master

pages/am/3.x/installation-guide/installation-guide-production-ready.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-production-ready/index.html)
=> Fix production ready documentation for AM

_config.yml
=> docs: APIM 3.16.2 has been released

_config.yml, pages/am/3.x/installation-guide/installation-guide-migration.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/release-3-17/index.html)
=> doc(am): addition of migration guide for release 3.17

_config.yml, pages/cockpit/changelog.adoc, pages/cockpit/installation-guide/installation-guide-introduction.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/cockpit-3-17/index.html)
=> docs: add cockpit 3.17 cockpit changelog

pages/apim/3.x/installation-guide/upgrades/3.17.0/README.adoc
see https://github.com/gravitee-io/issues/issues/7041
=> docs: add a note on the new location for mongodb upgrade scripts

pages/am/3.x/installation-guide/installation-guide-migration.adoc, pages/am/3.x/installation-guide/installation-guide-production-ready.adoc, pages/am/3.x/user-guide/mfa/user-guide-mfa-factors.adoc
related to https://github.com/gravitee-io/issues/issues/7415
related to https://github.com/gravitee-io/issues/issues/7418
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-fix-3-15-6/index.html)
=> fix(am): add migration guide for AM 3.15.6

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/user-guide/publisher/import-apis.adoc, pages/apim/3.x/user-guide/publisher/manage-apis/using-apis.adoc, pages/apim/3.x/user-guide/publisher/manage-apis/using-console.adoc, pages/apim/3.x/user-guide/publisher/partial-update-apis.adoc
gravitee-io/issues#7443
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/7443-patch-import/index.html)
=> feat(apim): add partial update documentation

pages/ee/overview/version.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/omatthewsgravitee-patch-1/index.html)
=> Update ee version on docs website

pages/apim/3.x/installation-guide/upgrades/3.18.0/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/7536
Add braking changes for audit management API
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/apim-3-18-audit-braking-changes/index.html)
=> Apim 3.18 audit braking changes

.circleci/config.yml
**Issue**
N/A
Replace SecretHub Orb with Keeper  Orb
=> ci: replace secrethub orb with keeper orb

pages/apim/3.x/user-guide/publisher/import-apis.adoc
docs(apim): add import API precision about id/crossId usage
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-crossidprecision/index.html)
=> docs(apim): add import API precision about id/crossId usage

pages/am/3.x/overview/introduction.adoc
**Issue**
Related to https://github.com/gravitee-io/issues/issues/7011
Added section about SAML in the overview of AM.
=> AM: Added section about SAML in /overview

pages/apim/3.x/user-guide/admin/admin-guide-users-and-groups.adoc
**Issue**
Update documentation for service account 
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/update-service-account/index.html)
=> docs(apim): update-service-account

pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-elasticsearch.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/7110
Add documentation on ILM configuration in APIM Gateway
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/add-documentation-on-apim-ilm-documentation/index.html)
=> docs: add information about ILM configuration in APIM Gateway

pages/apim/3.x/installation-guide/configuration/gateway/installation-guide-gateway-configuration.adoc, pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-mongodb.adoc, pages/apim/3.x/installation-guide/configuration/rest-apis/installation-guide-rest-apis-configuration.adoc
**Issue**
- https://github.com/gravitee-io/gravitee-api-management/pull/1641
- https://github.com/gravitee-io/_support_team/issues/151
Update SSL settings for mongo repository
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/151-update-mongo-config-attributes/index.html)
=> APIM: Update SSL settings for mongo repository

pages/apim/3.x/installation-guide/upgrades/3.18.0/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/7693
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/refactor-plansindefinition/index.html)
=> docs(apim): add plans data fix note in APIM 3.18 upgrade note

pages/am/3.x/installation-guide/configuration/installation-guide-gateway-configuration.adoc, pages/am/3.x/installation-guide/configuration/installation-guide-gateway-technical-api.adoc, pages/am/3.x/installation-guide/configuration/installation-guide-management-api-configuration.adoc, pages/am/3.x/installation-guide/configuration/installation-guide-management-api-technical-api.adoc, pages/am/3.x/installation-guide/partial/how-to-configure.adoc, pages/node/partial/technical-api-am.adoc
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-109
Update AM configuration document update.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/chore-109-review-configuration-guide/index.html)
=> chore(document): AM configuration updated.

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/user-guide/login/user-guide-login-redirect-users.adoc
closes gravitee-io/issues#7440
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/issues-7440-redirect-after-login/index.html)
=> am: add section about redirect users after login

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/installation-guide/configuration/reporters/installation-guide-reporters.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-reporters/index.html)
=> docs(apim): add reporter configuration section

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/installation-guide/configuration/installation-guide-gateway-metrics.adoc, pages/am/3.x/installation-guide/configuration/installation-guide-management-api-metrics.adoc, pages/am/3.x/installation-guide/monitoring/installation-guide-monitoring-prometheus.adoc, pages/am/3.x/installation-guide/monitoring/installation-guide-monitoring.adoc
Fixes https://graviteedevops.atlassian.net/browse/DOC-111
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-111-am-metrics/index.html)
=> doc(am): Addition of metrics description

pages/am/3.x/breaking-changes/breaking-changes-3.18.adoc, pages/am/3.x/installation-guide/installation-guide-migration.adoc
closes gravitee-io/issues#7939
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/issues-7939-webauthn-v2-doc/index.html)
=> am: breaking changes webauthn v2 javascript files

pages/ae/am/am-configuration.adoc, pages/am/3.x/user-guide/alerts/user-guide-alerts-notifications-partial.adoc, pages/am/3.x/user-guide/alerts/user-guide-alerts.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/7638
Documentation for risk-based alerts in AM
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-am-risk-assessment-alerts/index.html)
=> docs(am): risk-based alert documentation

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/installation-guide/amazon-linux/installation-guide-amazon-stack.adoc, pages/am/3.x/installation-guide/docker/installation-guide-docker-compose.adoc, pages/am/3.x/installation-guide/docker/installation-guide-docker-images.adoc, pages/am/3.x/installation-guide/docker/installation-guide-docker-introduction.adoc, pages/am/3.x/installation-guide/installation-guide-introduction.adoc, pages/am/3.x/installation-guide/kubernetes/installation-guide-helm-deployment-backends.adoc, pages/am/3.x/installation-guide/kubernetes/installation-guide-helm-deployment-ee.adoc, pages/am/3.x/installation-guide/kubernetes/installation-guide-helm-deployment.adoc, pages/am/3.x/installation-guide/kubernetes/installation-guide-helm-options.adoc, pages/am/3.x/installation-guide/kubernetes/installation-guide-kubernetes-introduction.adoc, pages/am/3.x/installation-guide/red-hat/installation-guide-redhat-introduction.adoc, pages/am/3.x/installation-guide/red-hat/installation-guide-redhat-stack.adoc, pages/am/3.x/installation-guide/zip/installation-guide-gateway-install-zip.adoc, pages/am/3.x/installation-guide/zip/installation-guide-management-api-install-zip.adoc, pages/am/3.x/installation-guide/zip/installation-guide-management-ui-install-zip.adoc, pages/am/3.x/installation-guide/zip/installation-guide-zip-introduction.adoc, pages/am/3.x/installation-guide/zip/installation-guide-zip-prerequisites.adoc
Fixes https://graviteedevops.atlassian.net/browse/DOC-104
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-104-am-dsc-installation/index.html)
=> doc(am): improve installation guides

pages/apim/3.x/installation-guide/installation-guide-migration.adoc, pages/apim/3.x/installation-guide/upgrades/3.16.5/README.adoc
**Issue**
NA
Add docs for APIM 3.16.5
=> Add docs for APIM 3.16.5

pages/apim/3.x/user-guide/publisher/expression-language.adoc
Update the example on the request headers access.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-request-headers/index.html)
=> docs(apim): update headers expression example

pages/am/3.x/user-guide/user-management/user/user-guide-users.adoc
related-to gravitee-io/issues#8085
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-3-15-11/index.html)
=> fix: add documentation to allow filtering on user additional information

pages/am/3.x/installation-guide/configuration/installation-guide-repositories-jdbc.adoc, pages/am/3.x/installation-guide/configuration/installation-guide-repositories-mongodb.adoc
fixes gravitee-io/issues#5856
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-3-18-1/index.html)
=> doc(am): SSL configuration for backends

_config.yml, _data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/breaking-changes/breaking-changes-3.17.2.adoc, pages/am/3.x/breaking-changes/breaking-changes-3.17.3.adoc, pages/am/3.x/breaking-changes/breaking-changes-3.17.4.adoc, pages/am/3.x/breaking-changes/breaking-changes-3.18.1.adoc, pages/am/3.x/breaking-changes/breaking-changes-3.18.2.adoc, pages/am/3.x/breaking-changes/breaking-changes-3.18.3.adoc, pages/am/3.x/breaking-changes/breaking-changes-3.18.adoc, pages/am/3.x/installation-guide/installation-guide-migration.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/8391
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-8391/index.html)
=> Breaking changes related to issue 8391

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/policy-reference/policy-circuit-breaker.adoc
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-178
https://github.com/gravitee-io/gravitee-docs/issues/843
Adding Circuit Breaker policy documentation to doc site
=> [DOC-178] Adding Circuit Breaker policy documentation to doc site

pages/apim/3.x/installation-guide/upgrades/3.10.19/README.adoc, pages/apim/3.x/installation-guide/upgrades/3.15.14/README.adoc, pages/apim/3.x/installation-guide/upgrades/3.18.7/README.adoc
DOC-225 Added warning note in upgrade notes for APIM 3.10.19 / 3.15.14 / 3.18.7
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-225
DOC-225 Added warning note in upgrade notes for APIM 3.10.19 / 3.15.14 / 3.18.7
=> DOC-225 Added warning note in upgrade notes for APIM 3.10.19 / 3.15.14 / 3.18.7

_config.yml, pages/apim/3.x/installation-guide/installation-guide-migration.adoc, pages/apim/3.x/installation-guide/upgrades/3.18.0/README.adoc, pages/apim/3.x/installation-guide/upgrades/3.18.9/README.adoc
**Issue**
N/A
Release of APIM 3.18.9
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/apim-3-18-9/index.html)
=> Release of APIM 3.18.9

pages/apim/3.x/installation-guide/upgrades/3.18.10/README.adoc
**Issue**
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/add-upgrade-for-3-18-10/index.html)
=> docs(apim): add upgrade guide for 3.18.10

pages/apim/3.x/kubernetes/apim-kubernetes-operator-api-reference.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-architecture.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-definitions.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-installation-cluster.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-installation-local.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-installation.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-overview.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-quick-start.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-api-definition.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-management-context.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-play.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-sync-crds.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-tools.adoc
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-194
https://app.zenhub.com/workspaces/graviteeio---api-management-601c1f73be51260015c7bb26/issues/gravitee-io/issues/8339
[DOC-194] GKO docs - updated overview and added notes and labels for v3.19.
[DOC-194]: https://graviteedevops.atlassian.net/browse/DOC-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-194-2/index.html)
=> [DOC-194] GKO docs update

pages/apim/3.x/installation-guide/upgrades/3.19.0/README.adoc
**Issue**
N/A
add breaking change on portal security header.
=> add breaking change on portal security header

pages/apim/3.x/kubernetes/apim-kubernetes-operator-installation-cluster.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-quick-start.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-gko-bundle-link/index.html)
=> docs: fix gko bundle release link

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/kubernetes/apim-kubernetes-operator-definitions.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-quick-start.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-api-definition.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-management-context.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-play.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-sync-crds.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide.adoc
DOC-234 Added notes about the correct sequence of CRD creation and fixed a broken link
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-234
DOC-234 Added notes about the correct sequence of CRD creation and fixed a broken link
=> DOC-234 Added notes about the correct sequence of CRD creation and fixed a broken link

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/kubernetes/apim-kubernetes-operator-api-reference.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-architecture.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-definitions.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-installation-cluster.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-installation-local.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-installation.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-overview.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-quick-start.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-api-definition.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-management-context.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-play.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-sync-crds.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-tools.adoc
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-234
DOC-234 Adding BETA release labels and text updates
=> DOC-234 Adding BETA release labels and text updates

_includes/footer.html
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-251
DOC-251 Redirected Algolia search to use the new app and API key
=> DOC-251 Redirected Algolia search to use the new app and API key

pages/apim/3.x/kubernetes/apim-kubernetes-operator-quick-start.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-play.adoc
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-249
DOC-249 Added a clarification about GW deployment in GKO docs
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-249/index.html)
=> DOC-249 Added a clarification about GW deployment in GKO docs

_config.yml, pages/ee/introduction.adoc
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-252
https://graviteedevops.atlassian.net/browse/DOC-228
* DOC-252 Removed CLI version entry from _config.yml 
* DOC-228 DOC-252 Updated list of EE plugins for AM
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-252/index.html)
=> DOC-252 DOC-228 Removed CLI version entry from _config.yml and and updated list of EE plugins for AM

pages/apim/3.x/kubernetes/apim-kubernetes-operator-definitions.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-quick-start.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-api-definition.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-management-context.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-play.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-gko-context/index.html)
=> docs: update gko context section

pages/apim/3.x/installation-guide/with-zip/installation-guide-gateway-install-zip.adoc, pages/apim/3.x/installation-guide/with-zip/installation-guide-management-ui-install-zip.adoc, pages/apim/3.x/installation-guide/with-zip/installation-guide-portal-ui-install-zip.adoc, pages/apim/3.x/installation-guide/with-zip/installation-guide-rest-apis-install-zip.adoc, pages/apim/3.x/installation-guide/with-zip/partial/download-and-extract-zip-file.adoc
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-115
Related to:
https://graviteedevops.atlassian.net/browse/DOC-43
* share code about how to download full zip and extract component
* use it in each component page with the right names
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-zip-installation-guide/index.html)
=> APIM Installatuin Guide: Rewrite zip file installation documentation

pages/apim/3.x/how-tos/how-to-general-configuration.adoc
**Issue**
https://graviteedevops.atlassian.net/browse/VM-156
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/add-nginx-header-option/index.html)
=> docs(apim): configuration to avoid Cross Site Framing

pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-sync-crds.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-kubectl-gko/index.html)
=> docs: fix kubectl shell commands for GKO resources

pages/apim/3.x/kubernetes/apim-kubernetes-operator-installation-local.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/chore-update-k3d-to-zx/index.html)
=> docs: update k3d script section to use zx instead of bash

pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-management-context.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-gko-secret-ref/index.html)
=> docs: update gko docs with context secret ref

pages/apim/3.x/installation-guide/installation-guide-migration.adoc, pages/apim/3.x/installation-guide/upgrades/3.15.17/README.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/3-15-17-upgrade/index.html)
=> docs(apim): add upgrade note for 3.15.17

pages/apim/3.x/user-guide/publisher/expression-language.adoc
Adding some enhancements from the spring clean doc day on Expression Language.
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-30
=> docs(apim): enhancements-on-expression-language

pages/am/3.x/user-guide/branding/user-guide-branding.adoc
**Issue**
From https://graviteedevops.atlassian.net/browse/DOC-185
Re-wrote the Banding overview page + added more info around execution context
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-am-doc-185-branding-overview-re-write/index.html)
=> Re-wrote branding overview, adding more info around exection context

pages/am/3.x/breaking-changes/breaking-changes-3.15.10.adoc, pages/am/3.x/installation-guide/installation-guide-migration.adoc
related-to gravitee-io/issues#7800
Please do no mere this PR until the 3.15.10 is out.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-3-15-10/index.html)
=> fix(am 3.15): add breaking change note about HTTP Idp

pages/apim/3.x/user-guide/publisher/expression-language.adoc
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-276
DOC-276 Expression language section update
Addressing comment https://github.com/gravitee-io/gravitee-docs/pull/773#discussion_r909214052
=> DOC-276 [APIM] Expression language section update

pages/am/3.x/breaking-changes/breaking-changes-3.18.adoc, pages/am/3.x/user-guide/mfa/user-guide-mfa-risk-based.adoc
Added note for the consent variables.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-update-3-18-6-doc/index.html)
=> chore(document): added note in the breaking change

am/current/account/3.15/index.html, am/current/account/3.15/swagger.yml, am/current/account/3.16/index.html, am/current/account/3.16/swagger.yml, am/current/account/3.17/index.html, am/current/account/3.17/swagger.yml, am/current/account/3.18/index.html, am/current/account/3.18/swagger.yml, am/current/account/3.19/index.html, am/current/account/3.19/swagger.yml, pages/am/3.x/user-guide/user-management/self-service-account/user-guide-ssam-overview.adoc
closes AM-155
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-155-gateway-self-service-account-doc-update-api-reference/index.html)
=> am: add missing self service account API references

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/kubernetes/apim-kubernetes-operator-definitions.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-overview.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-reusable-resources.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide.adoc
https://graviteedevops.atlassian.net/browse/DOC-279
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/gko-resource-doc/index.html)
=> DOC-279 docs: add api resource definition to gko crds

pages/apim/3.x/kubernetes/apim-kubernetes-operator-quick-start.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-play.adoc
=> Link fix gko

pages/apim/3.x/kubernetes/apim-kubernetes-operator-quick-start.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-play.adoc
=> Link fixes

.github/CODEOWNERS, pages/apim/1.x/changelog.adoc
**Issue**
N/A
Move Gravitee v1.* changelog in doc and remove import from api-management monorepo
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/changelog-v1/index.html)
=> feat: move Gravetee 1.* changelog

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/changelog.adoc, pages/apim/3.x/changelog/changelog-3.15.adoc, pages/apim/3.x/changelog/changelog-3.18.adoc, pages/apim/3.x/changelog/changelog-3.19.adoc, pages/apim/3.x/changelog/changelog-eos.adoc
**Issue**
https://gravitee.atlassian.net/browse/APIM-367
Init new changelog section in order to replace old changelog imported from apim repo
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/apim-release-notes/index.html)
=> APIM - Init new Changelog

pages/apim/3.x/kubernetes/apim-kubernetes-operator-installation-cluster.adoc
Watch all namespaces using the Gravitee Kubernetes Operateur
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/feat-listen-all-namespaces/index.html)
=> docs(apim): look for gko api definitions in all namespaces

pages/apim/3.x/changelog/changelog-3.19.adoc
**Issue**
Comment example part of changelog
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-commented-stuff/index.html)
=> fix(docs):comment-example

_data/sidebars/ee_sidebar.yml, pages/ee/installation.adoc, pages/ee/introduction.adoc, pages/ee/version.adoc
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-289
Changed EE versioning page link and references to that page
=> DOC-289 Updated EE versioning page permalink and references

.github/CODEOWNERS
**Issue**
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-changelog/index.html)
=> ask @gravitee-io/tech-writers to review each PR

pages/ae/apim/apim-notification-request.adoc
**Issue**
Next to : https://graviteesource.zendesk.com/agent/tickets/5275
n/a
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/thibaudav-patch-1/index.html)
=> fix: typo in ae notification request

pages/apim/3.x/changelog/changelog-3.18.adoc
=> Add link to GH issues

pages/apim/3.x/changelog/changelog-3.18.adoc
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-296
Added updates as [provided on Slack](https://graviteeio.slack.com/archives/C04FED64J4W/p1671541449621259).
=> Added updates as provided on Slack

_config.yml, _data/sidebars/ae_sidebar.yml, ae/spec/2.0/alert-engine-spec.yml, ae/spec/2.0/index.html, pages/ae/3rdparties/3rdparties-installation.adoc, pages/ae/apim/apim-installation.adoc, pages/ae/installation-guide/installation-guide-configuration.adoc, pages/ae/installation-guide/installation-guide-migration.adoc, pages/ae/installation-guide/installation-guide-sizing-requirements.adoc
This is a Draft for the AE 2.0
Still in WIP
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/ae-2-0/index.html)
=> docs(ae): AE 2.0 - 3rd party installation - API spec

pages/apim/3.x/installation-guide/installation-guide-migration.adoc, pages/apim/3.x/installation-guide/upgrades/3.15.20/README.adoc
**Issue**
N/A
Add information in the upgrade guide for the 3.15.20 version of APIM. (This is **not** the changelog 😉)
=> Update upgrade guide for APIM 3.15.20

pages/apim/3.x/installation-guide/installation-guide-migration.adoc, pages/apim/3.x/installation-guide/upgrades/3.18.15/README.adoc, pages/apim/3.x/installation-guide/upgrades/3.18.16/README.adoc, pages/apim/3.x/installation-guide/upgrades/3.19.5/README.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-3-18-0-liquibase-changeset/index.html)
=> docs: add upgrade warning for jdbc users

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/changelog/changelog-3.20.adoc
**Issue**
https://gravitee.atlassian.net/browse/DOC-299
Initial draft of changelog for 3.20
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-299/index.html)
=> APIM 3.20.0 changelog

pages/ae/am/am-installation.adoc, pages/ae/apim/apim-installation.adoc
**Issue**
Related issue: 
https://gravitee.atlassian.net/browse/AE-46
(can be merged before hand)
This PR demonstrate how to configure ssl with the AE connector
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-ae-connector-ssl/index.html)
=> fix(ae): ssl configuration on AE connector

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/kubernetes/apim-kubernetes-operator-monitoring.adoc
**Issue**
https://gravitee.atlassian.net/jira/software/c/projects/APIM/boards/3?modal=detail&selectedIssue=APIM-361
Add a section in the operator about the monitoring using prometheus and grafana 
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/apim-361-gko-monitoring/index.html)
=> docs(apim): add gko monitoring section

pages/apim/3.x/changelog/changelog-3.18.adoc
**Issue**
N/A
This reverts commit 0175c465daaa61030f05699d298a9411db054e44.
the GH Issue mentioned in the changelog will be fixed in 3.18.18
=> Revert "Update changelog-3.18.adoc"

pages/ee/license.adoc
Corrected indentation in some YAML
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-330/index.html)
=> Correcting indentation

pages/apim/3.x/changelog/changelog-3.15.adoc, pages/apim/3.x/changelog/changelog-3.18.adoc, pages/apim/3.x/changelog/changelog-eos.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-docs/edit/release-apim-3.18.19/pages/apim/3.x/changelog/changelog-3.18.adoc)
<details>
- fix: update validation spec in API proxy config schema form
- fix(repository): use default application.findAll to have group filled
- fix: display redundant spaces in API, Application and Plan deletion popup
- fix: set sync probe to true when caches are fully loaded
- fix: sanitize name of new API
- fix: sanitize name and description of new Plan
- fix: sanitize name and description of new Application
- fix: sanitize firstname and lastname of NewExternalUserEntity
- fix: stop the dynamic properties service when it's …
=> [APIM] Add changelog for new 3.18.19 release

pages/apim/3.x/changelog/changelog-3.18.adoc
**Issue**
NA
Fix link in changelog of APIM 3.18.19
=> Fix link in changelog of APIM 3.18.19

pages/apim/3.x/quickstart/quickstart-overview.adoc, pages/apim/3.x/user-guide/publisher/manage-apis/using-apis.adoc
**Issue**
https://gravitee.atlassian.net/browse/DOC-346
Small changes to fix doc build warnings.
=> Fixing malformed link

pages/apim/3.x/v4/event-native-tutorials-kafka-webhooks.adoc, pages/apim/3.x/v4/event-native-tutorials-mqtt-webhooks.adoc
**Issue**
https://gravitee.atlassian.net/browse/DOC-348
Correcting an issue with the `type`.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-348/index.html)
=> Correcting the type.

pages/am/3.x/user-guide/branding/user-guide-branding-theme-language-properties.adoc
**Issue**
https://gravitee.atlassian.net/browse/AM-503
This PR adds the mfa phone call i18n template variables
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-503-phone-call-template-docs/index.html)
=> docs(am): phone call mfa template variables

pages/apim/3.x/installation-guide/installation-guide-migration.adoc, pages/apim/3.x/installation-guide/upgrades/3.18.21/README.adoc, pages/apim/3.x/installation-guide/upgrades/3.19.9/README.adoc, pages/apim/3.x/installation-guide/upgrades/3.20.3/README.adoc
https://gravitee.atlassian.net/browse/APIM-851
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/docs-upgrade-3-18-21/index.html)
=> docs: add upgrade guide for 3.18.21

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/dev-guide/protocols/oauth2/protocols_oauth2_refresh_tokens_get.adoc, pages/am/3.x/dev-guide/protocols/oauth2/protocols_oauth2_refresh_tokens_overview.adoc, pages/am/3.x/dev-guide/protocols/oauth2/protocols_oauth2_refresh_tokens_revoke.adoc, pages/am/3.x/dev-guide/protocols/oauth2/protocols_oauth2_refresh_tokens_rotation.adoc, pages/am/3.x/dev-guide/protocols/oauth2/protocols_oauth2_refresh_tokens_use.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-refresh-token-revamp/index.html)
=> am: add a dedicated section for the OAuth 2.0 Refresh Tokens

pages/am/3.x/changelog.adoc
=> Use our internal DNS to fetch the AM changelog

pages/apim/3.x/kubernetes/apim-kubernetes-operator-quick-start.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-play.adoc
Some links are outdated 😿 Here is a pr to update it
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/gko-doc/index.html)
=> docs: update GKO documentation links

pages/apim/3.x/changelog/changelog-3.18.adoc
**Issue**
N/A
Add missing fixed issue in APIM 3.18.20 changelog
=> fix: add missing fixed issue

pages/ee/version.adoc
**Issue**
https://gravitee.atlassian.net/browse/DOC-350
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-350/index.html)
=> Updating release table

pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-sync-crds.adoc
**Issue**
https://gravitee.atlassian.net/browse/DOC-353
Link corrected.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-353/index.html)
=> Link corrected.

pages/apim/3.x/user-guide/admin/admin-guide-roles-and-permissions.adoc
**Issue**
https://gravitee.atlassian.net/browse/APIM-861
Change GATEWAY_DEFINITION role description
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/apim-roles/index.html)
=> docs: update apim GATEWAY_DEFINITION role description

_config.yml, pages/ae/installation-guide/installation-guide-docker.adoc
Upgrades AE to the latest version
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/ae-upgrade-latest-version/index.html)
=> chore(ae): upgrade to latest AE version

pages/apim/3.x/changelog/changelog-3.18.adoc
**Issue**
NA
Add missing item in changelog of APIM 3.18.22
=> Add missing item in changelog of APIM 3.18.22

pages/ae/installation-guide/installation-guide-docker.adoc, pages/ae/installation-guide/installation-guide-kubernetes.adoc, pages/am/1.x/installation-guide/installation-guide-docker.adoc, pages/apim/3.x/dev-guide/dev-guide-boostrap.adoc, pages/apim/3.x/user-guide/publisher/manage-apis/using-console.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-contributing-link/index.html)
=> fix: update contributing link to use the Gravitee DNS

_data/sidebars/apim_3_x_sidebar.yml, pages/apim/3.x/kubernetes/apim-kubernetes-operator-definitions.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-quick-start.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-api-definition.adoc, pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-application.adoc
**Issue**
https://gravitee.atlassian.net/browse/APIM-769
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/application-crd/index.html)
=> docs: add docs for the application CRD

pages/apim/3.x/changelog/changelog-3.18.adoc, pages/apim/3.x/changelog/changelog-3.19.adoc, pages/apim/3.x/changelog/changelog-3.20.adoc
**Issue**
NA
Add missing changelog entries
=> Add missing changelog entries

pages/apim/3.x/kubernetes/apim-kubernetes-operator-user-guide-play.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-kub-sync-env-var/index.html)
=> docs: fix kubernetes sync env var name

_includes/head.html
Add integration with [Reo analytics](https://www.reo.dev/) for demand gen.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/reo-integration/index.html)
=> build: add reo integration

_includes/head.html
This reverts commit b938e4612783d744869c87e2179ab7973cff91d4.
**Issue**
Some users reported an issue when they browse the docs website they get a 400 error.
=> Revert "build: add reo integration"

pages/apim/1.x/installation-guide/installation-guide-kubernetes.adoc, pages/apim/3.x/installation-guide/installation-guide-kubernetes.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/fix-helm-link/index.html)
=> docs: fix apim helm links

pages/apim/3.x/changelog/changelog-3.18.adoc, pages/apim/3.x/changelog/changelog-3.19.adoc, pages/apim/3.x/changelog/changelog-3.20.adoc
**Issue**
NA
Add missing issue and highlight 3.18 EoS
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/add-missing-issue/index.html)
=> Add missing issue and highlight 3.18 EoS

_includes/topnav.html, css/theme-gravitee_new.css
**Issue**
NA
Add a banner with a link to the new doc website. It needs to be completed @gravitee-io/tech-writers, I've put `UPDATE ME` where needed.
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/add-banner-for-new-doc-website/index.html)
=> Add a banner with a link to the new doc website

_data/sidebars/am_3_x_sidebar.yml, pages/am/3.x/breaking-changes/breaking-changes.adoc
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/am-fix-missing-breaking-change-link/index.html)
=> am(menu): fixed missing breaking changes

.github/CODEOWNERS
**Issue**
Na
Restore CODEOWNER file
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/restore-codeowners/index.html)
=> Restore CODEOWNER file

pages/am/3.x/installation-guide/red-hat/installation-guide-redhat-gateway.adoc, pages/am/3.x/installation-guide/red-hat/installation-guide-redhat-management-api.adoc, pages/am/3.x/installation-guide/red-hat/installation-guide-redhat-management-ui.adoc, pages/am/3.x/installation-guide/red-hat/installation-guide-redhat-stack.adoc, pages/apim/3.x/installation-guide/red-hat/installation-guide-redhat-management-ui.adoc
**Issue**
https://gravitee.atlassian.net/browse/DV-309
feat: update doc about APIM upgrade installation on redhat
🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/feat-dv-309-update-changelog-and-documentation-about-rpm-upg/index.html)
=> feat: update doc about AM upgrade installation on redhat
